version: "3"

volumes:
  web_build:


services:
  db:
    container_name: zufms_db
    image: postgres:14.2-alpine
    env_file: ./infra/database/.env
    volumes:
      - ./infra/database/postgres/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/:z
  api:
    container_name: zufms_api
    build: ./api
    depends_on:
      - db
  api_docs:
    container_name: zufms_api_docs
    image: swaggerapi/swagger-ui
    environment:
      - API_URL=https://localhost/docs/v1/openapi.yml
  web:
    container_name: zufms_web
    build: 
      context: ./web
      dockerfile: Dockerfile.prod
    volumes:
      - web_build:/app/dist:z
  redis:
    container_name: zufms_redis
    image: redis:7.0-alpine
    env_file: ./infra/database/.env
    command: redis-server --loglevel warning --requirepass secret
  redis_adapter:
    container_name: zufms_redis_adapter
    env_file: ./infra/database/.env
    build:
      context: ./infra/database/redis/http_adapter
      args:
        - REDIS_ADAPTER_PORT=$${REDIS_ADAPTER_PORT}
        - REDIS_CONNECTION_URL=$${REDIS_CONNECTION_URL}
    depends_on:
      - redis
  http:
    container_name: zufms_http
    image: nginx:1.21
    ports:
      - "443:443"
      - "80:80"
      - "3030:3030"
    volumes:
      - ./infra/http/nginx/nginx.conf:/etc/nginx/nginx.conf:z
      - ./infra/http/nginx/conf.d.prod/:/etc/nginx/conf.d/:z
      - ./infra/http/certificates/:/etc/nginx/certificates/:z
      - web_build:/app/web:z
      - ./docs/openapi.yml:/app/docs/openapi.yml:z
    depends_on:
      - api
      - web
      - redis_adapter
      - api_docs
