/* tslint:disable */
/* eslint-disable */
/**
 * Coleção Zoológica Online ZUFMS
 * Coleção Zoológica – Incremento e movimentação do acervo  ## Visão geral 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: suporte.agetic@ufms.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ErrorResponse,
    ErrorResponseFromJSON,
    ErrorResponseFromJSONTyped,
    ErrorResponseToJSON,
} from './ErrorResponse';
import {
    InsufficientPermissionsError,
    InsufficientPermissionsErrorFromJSON,
    InsufficientPermissionsErrorFromJSONTyped,
    InsufficientPermissionsErrorToJSON,
} from './InsufficientPermissionsError';

/**
 * 
 * @export
 * @interface InsufficientPermissionsErrorResponse
 */
export interface InsufficientPermissionsErrorResponse {
    /**
     * 
     * @type {Array<InsufficientPermissionsError>}
     * @memberof InsufficientPermissionsErrorResponse
     */
    errors?: Array<InsufficientPermissionsError>;
}

export function InsufficientPermissionsErrorResponseFromJSON(json: any): InsufficientPermissionsErrorResponse {
    return InsufficientPermissionsErrorResponseFromJSONTyped(json, false);
}

export function InsufficientPermissionsErrorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InsufficientPermissionsErrorResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'errors': !exists(json, 'errors') ? undefined : ((json['errors'] as Array<any>).map(InsufficientPermissionsErrorFromJSON)),
    };
}

export function InsufficientPermissionsErrorResponseToJSON(value?: InsufficientPermissionsErrorResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'errors': value.errors === undefined ? undefined : ((value.errors as Array<any>).map(InsufficientPermissionsErrorToJSON)),
    };
}

