/* tslint:disable */
/* eslint-disable */
/**
 * Coleção Zoológica Online ZUFMS
 * Coleção Zoológica – Incremento e movimentação do acervo  ## Visão geral 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: suporte.agetic@ufms.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequestCodeRequest
 */
export interface RequestCodeRequest {
    /**
     * 
     * @type {string}
     * @memberof RequestCodeRequest
     */
    email?: string;
}

export function RequestCodeRequestFromJSON(json: any): RequestCodeRequest {
    return RequestCodeRequestFromJSONTyped(json, false);
}

export function RequestCodeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestCodeRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': !exists(json, 'email') ? undefined : json['email'],
    };
}

export function RequestCodeRequestToJSON(value?: RequestCodeRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
    };
}

