/* tslint:disable */
/* eslint-disable */
/**
 * Coleção Zoológica Online ZUFMS
 * Coleção Zoológica – Incremento e movimentação do acervo  ## Visão geral 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: suporte.agetic@ufms.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RevokeAccessTokenRequest
 */
export interface RevokeAccessTokenRequest {
    /**
     * 
     * @type {string}
     * @memberof RevokeAccessTokenRequest
     */
    clientId?: string;
    /**
     * 
     * @type {string}
     * @memberof RevokeAccessTokenRequest
     */
    clientSecret?: string;
    /**
     * 
     * @type {string}
     * @memberof RevokeAccessTokenRequest
     */
    clientToken?: string;
}

export function RevokeAccessTokenRequestFromJSON(json: any): RevokeAccessTokenRequest {
    return RevokeAccessTokenRequestFromJSONTyped(json, false);
}

export function RevokeAccessTokenRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RevokeAccessTokenRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'clientId': !exists(json, 'client_id') ? undefined : json['client_id'],
        'clientSecret': !exists(json, 'client_secret') ? undefined : json['client_secret'],
        'clientToken': !exists(json, 'client_token') ? undefined : json['client_token'],
    };
}

export function RevokeAccessTokenRequestToJSON(value?: RevokeAccessTokenRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'client_id': value.clientId,
        'client_secret': value.clientSecret,
        'client_token': value.clientToken,
    };
}

