/* tslint:disable */
/* eslint-disable */
/**
 * Coleção Zoológica Online ZUFMS
 * Coleção Zoológica – Incremento e movimentação do acervo  ## Visão geral 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: suporte.agetic@ufms.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserAuthRequest
 */
export interface UserAuthRequest {
    /**
     * 
     * @type {string}
     * @memberof UserAuthRequest
     */
    type?: UserAuthRequestTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof UserAuthRequest
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof UserAuthRequest
     */
    code?: string;
}

/**
* @export
* @enum {string}
*/
export enum UserAuthRequestTypeEnum {
    Password = 'password'
}

export function UserAuthRequestFromJSON(json: any): UserAuthRequest {
    return UserAuthRequestFromJSONTyped(json, false);
}

export function UserAuthRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserAuthRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': !exists(json, 'type') ? undefined : json['type'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'code': !exists(json, 'code') ? undefined : json['code'],
    };
}

export function UserAuthRequestToJSON(value?: UserAuthRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'email': value.email,
        'code': value.code,
    };
}

