INSERT INTO "biological_occurrence_view" (
    "artificial:section",
    "dcterms:modified",
    "informationWithheld",
    "basisOfRecord",
    "institutionCode",
    "collectionCode",
    "dcterms:bibliographicCitation",
    "datasetName",
    "artificial:shelfLocation",
    "artificial:flaskLocation",
    "artificial:shippingGuide",
    "catalogNumber",
    "otherCatalogNumbers",
    "recordedBy",
    "recordNumber",
    "preparations",
    "individualCount",
    "sex",
    "lifeStage",
    "reproductiveCondition",
    "establishmentMeans",
    "behavior",
    "occurrenceRemarks",
    "disposition",
    "associatedReferences",
    "associatedMedia",
    "occurrenceID",
    "associatedOccurrences",
    "previousIdentifications",
    "fieldNumber",
    "day",
    "month",
    "year",
    "eventTime",
    "eventDate",
    "verbatimEventDate",
    "samplingProtocol",
    "habitat",
    "eventRemarks",
    "fieldNotes",
    "measurementRemarks",
    "continent",
    "country",
    "countryCode",
    "verbatimLocality",
    "stateProvince",
    "county",
    "municipality",
    "locality",
    "decimalLatitude",
    "decimalLongitude",
    "verbatimLatitude",
    "verbatimLongitude",
    "coordinatePrecision",
    "geodeticDatum",
    "footprintWKT",
    "minimumElevationInMeters",
    "maximumElevationInMeters",
    "waterBody",
    "minimumDepthInMeters",
    "maximumDepthInMeters",
    "locationRemarks",
    "identificationQualifier",
    "identifiedBy",
    "dateIdentified",
    "typeStatus",
    "scientificName",
    "scientificNameAuthorship",
    "acceptedNameUsage",
    "subgenus",
    "genus",
    "family",
    "order",
    "class",
    "phylum",
    "kingdom",
    "artificial:subfamily",
    "specificEpithet",
    "infraspecificEpithet",
    "taxonRank",
    "taxonomicStatus",
    "originalNameUsage",
    "vernacularName",
    "nomenclaturalCode",
    "nameAccordingTo",
    "relationshipOfResource"
) 
VALUES 
    (
        'Amphibia',
        '2017-08-28',
        'verificar amostra de tecido',
        'PreservedSpecimen',
        'UFMS',
        'ZUFMS',
        'Oliver P. Pearson. 1985. Los tuco-tucos (genera Ctenomys) de los Parques Nacionales Lanin y Nahuel Huapi, Argentina Historia Natural, 5(37):337-343.',
        'Projeto Jauru',
        'P001',
        'AMPAA',
        'GR07/2017',
        'ZUFMS-CRU00001',
        'CHAFB0001',
        'BÉDA, A. F.',
        '0003',
        'animal inteiro (ETOH); tecido (EDTA)',
        '1',
        'macho',
        'adulto',
        'não reprodutivo',
        'selvagem',
        'vocalizando',
        'espécime encontrado morto na estrada',
        'na coleção',
        'GALLARDO, Fabiana E.; RECHE, Vanina A.; MONTEIRO, Ricardo Ferreira. New data on Marthiella Buffington (Hymenoptera, Cynipoidea, Figitidae), with description of a new species. Rev. Bras. entomol., São Paulo ,  v. 58, n. 2, jun.  2014',
        'inbio.br/photo.jpg',
        'br:UFMS:ZUFMS-CRU00001',
        'ZUFMS-LEP00001|ZUFMS-COL00002',
        'Anthus sp., ID de campo por G. Iglesias; Anthus correndera, ID do experto por C. Cicero 2009-02-12 baseado em morfologia',
        'Pitfall0001Seca',
        '20',
        '12',
        '1994',
        '{}',
        '{}',
        '17.IV.2015',
        'busca ativa',
        'Pantanal',
        'após das recentes chuvas o rio está quase na fase de inundação',
        'notas disponíveis na Biblioteca Central',
        'antebraço (mm): 47,1; peso (g): 23',
        'América do Sul',
        'Brasil',
        'BRA',
        'Bacia do Paraguai',
        'Mato Grosso do Sul',
        'Corguinho',
        'Taboco',
        'Fazenda Nhumirim',
        '-45.62189',
        '-21.89742',
        '21°31''23.40"S',
        '56°32''45.52"W',
        '10',
        'WGS84',
        'GPS: 019°18''00"S--021°39''00"S/056°22''00"W--053°34''00"W',
        '100',
        '100',
        'Rio Salobra',
        '100',
        '100',
        'debaixo de água desde 2005',
        'cf.',
        'GRACIOLLI, G.',
        '2012-03-27',
        'holótipo',
        'Dilocarcinus (Dilocarcinus) pagei pagei',
        'Stimpson, 1861',
        'Dilocarcinus (Dilocarcinus) pagei pagei Stimpson, 1861',
        'Dilocarcinus',
        'Dilocarcinus',
        'Leptodactylidae',
        'Anura',
        'Reptilia',
        'Chordata',
        'Animalia',
        'Leptodactylinae',
        'pagei',
        'pagei',
        'subespécie',
        'em descrição',
        'Dilocarcinus pagei Stimpson, 1861',
        'caramujo-d''água',
        'ICZN',
        'Frost, 2017',
        'presa'
    ), 
    (
        'Amphibia',
        '2017-08-28',
        'verificar amostra de tecido',
        'PreservedSpecimen',
        'UFMS',
        'ZUFMS',
        'Oliver P. Pearson. 1985. Los tuco-tucos (genera Ctenomys) de los Parques Nacionales Lanin y Nahuel Huapi, Argentina Historia Natural, 5(37):337-343.',
        'Projeto Jauru',
        'P001',
        'AMPAA',
        'GR07/2017',
        'ZUFMS-CRU00002',
        'CHAFB0001',
        'BÉDA, A. F.',
        '0003',
        'animal inteiro (ETOH); tecido (EDTA)',
        '1',
        'macho',
        'adulto',
        'não reprodutivo',
        'selvagem',
        'vocalizando',
        'espécime encontrado morto na estrada',
        'na coleção',
        'GALLARDO, Fabiana E.; RECHE, Vanina A.; MONTEIRO, Ricardo Ferreira. New data on Marthiella Buffington (Hymenoptera, Cynipoidea, Figitidae), with description of a new species. Rev. Bras. entomol., São Paulo ,  v. 58, n. 2, jun.  2014',
        'inbio.br/photo.jpg',
        'br:UFMS:ZUFMS-CRU00002',
        'ZUFMS-LEP00001|ZUFMS-COL00002',
        'Anthus sp., ID de campo por G. Iglesias; Anthus correndera, ID do experto por C. Cicero 2009-02-12 baseado em morfologia',
        'Pitfall0001Seca',
        '20',
        '12',
        '1994',
        '{}',
        '{}',
        '17.IV.2015',
        'busca ativa',
        'Pantanal',
        'após das recentes chuvas o rio está quase na fase de inundação',
        'notas disponíveis na Biblioteca Central',
        'antebraço (mm): 47,1; peso (g): 23',
        'América do Sul',
        'Brasil',
        'BRA',
        'Bacia do Paraguai',
        'Mato Grosso do Sul',
        'Corguinho',
        'Taboco',
        'Fazenda Nhumirim',
        '-45.62189',
        '-21.89742',
        '21°31''23.40"S',
        '56°32''45.52"W',
        '10',
        'WGS84',
        'GPS: 019°18''00"S--021°39''00"S/056°22''00"W--053°34''00"W',
        '100',
        '100',
        'Rio Salobra',
        '100',
        '100',
        'debaixo de água desde 2005',
        'cf.',
        'GRACIOLLI, G.',
        '2012-03-27',
        'holótipo',
        'Dilocarcinus (Dilocarcinus) pagei pagei',
        'Stimpson, 1861',
        'Dilocarcinus (Dilocarcinus) pagei pagei Stimpson, 1861',
        'Dilocarcinus',
       null,
        'Leptodactylidae',
        'Anura',
        'Reptilia',
        'Chordata',
        'Animalia',
       null,
        'pagei',
        'pagei',
        'subespécie',
        'em descrição',
        'Dilocarcinus pagei Stimpson, 1861',
        'caramujo-d''água',
        'ICZN',
        'Frost, 2017',
        'presa'
    );
