array:6 [
  0 => array:1 [
    0 => array:3 [
      "query" => "insert into "biological_occurrence_view" ("informationWithheld", "basisOfRecord", "institutionCode", "collectionCode", "datasetName", "catalogNumber", "otherCatalogNumbers", "recordedBy", "recordNumber", "preparations", "individualCount", "sex", "lifeStage", "reproductiveCondition", "establishmentMeans", "behavior", "occurrenceRemarks", "disposition", "associatedReferences", "associatedMedia", "occurrenceID", "associatedOccurrences", "previousIdentifications", "fieldNumber", "day", "month", "year", "verbatimEventDate", "samplingProtocol", "habitat", "eventRemarks", "fieldNotes", "measurementRemarks", "continent", "country", "countryCode", "verbatimLocality", "stateProvince", "county", "municipality", "locality", "decimalLatitude", "decimalLongitude", "verbatimLatitude", "verbatimLongitude", "coordinatePrecision", "geodeticDatum", "footprintWKT", "minimumElevationInMeters", "maximumElevationInMeters", "waterBody", "minimumDepthInMeters", "maximumDepthInMeters", "locationRemarks", "identificationQualifier", "identifiedBy", "dateIdentified", "typeStatus", "scientificName", "scientificNameAuthorship", "acceptedNameUsage", "subgenus", "genus", "family", "order", "class", "phylum", "kingdom", "specificEpithet", "infraspecificEpithet", "taxonRank", "taxonomicStatus", "originalNameUsage", "vernacularName", "nomenclaturalCode", "nameAccordingTo", "relationshipOfResource", "dcterms:modified", "artificial:section", "artificial:shelfLocation", "artificial:flaskLocation", "artificial:shippingGuide", "artificial:subfamily", "artificial:subtribe", "artificial:tribe", "artificial:superfamily", "artificial:infraorder", "artificial:superorder", "artificial:suborder", "artificial:subclass", "artificial:subphylum", "dcterms:bibliographicCitation") values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"
      "bindings" => array:92 [
        0 => "nenhuma"
        1 => "PreservedSpecimen"
        2 => "UFMS"
        3 => "ZUFMS"
        4 => "material em estudo por Carla Kampião"
        5 => "ZUFMS-ACA00001"
        6 => null
        7 => "Campião, K. et al."
        8 => "93"
        9 => "animal inteiro (ETOH 70%)"
        10 => "9"
        11 => null
        12 => null
        13 => null
        14 => "selvagem"
        15 => "não informado"
        16 => "parasita de Phyllomedusa azurea (Amphibia: Hylidae)"
        17 => "em coleção"
        18 => null
        19 => null
        20 => "br:UFMS:ZUFMS:ZUFMS-ACA00001"
        21 => null
        22 => null
        23 => null
        24 => 3
        25 => 2
        26 => 2011
        27 => "03.II.2011"
        28 => null
        29 => null
        30 => null
        31 => null
        32 => null
        33 => "América do Sul"
        34 => "Brasil"
        35 => "BRA"
        36 => "Brasil"
        37 => "Mato Grosso do Sul"
        38 => "Corumbá"
        39 => ""
        40 => "Fazenda Alegria"
        41 => -18.983333
        42 => -56.65
        43 => "18°59'00"S"
        44 => "56°39'00"W"
        45 => 0.0
        46 => "WGS84"
        47 => null
        48 => 0.0
        49 => 0.0
        50 => null
        51 => 0.0
        52 => 0.0
        53 => null
        54 => null
        55 => "Campião, K."
        56 => null
        57 => null
        58 => "Acanthocephala"
        59 => null
        60 => "Acanthocephala"
        61 => null
        62 => null
        63 => null
        64 => null
        65 => null
        66 => "Acanthocephala"
        67 => "Animalia"
        68 => null
        69 => null
        70 => "filo"
        71 => null
        72 => null
        73 => null
        74 => "ICZN"
        75 => null
        76 => "nenhum"
        77 => "2017-08-30"
        78 => "Acanthocephala"
        79 => null
        80 => null
        81 => null
        82 => null
        83 => null
        84 => null
        85 => null
        86 => null
        87 => null
        88 => null
        89 => null
        90 => null
        91 => null
      ]
      "time" => 45.67
    ]
  ]
  1 => array:3 [
    0 => array:3 [
      "query" => "insert into "biological_occurrence_view" ("informationWithheld", "basisOfRecord", "institutionCode", "collectionCode", "datasetName", "catalogNumber", "otherCatalogNumbers", "recordedBy", "recordNumber", "preparations", "individualCount", "sex", "lifeStage", "reproductiveCondition", "establishmentMeans", "behavior", "occurrenceRemarks", "disposition", "associatedReferences", "associatedMedia", "occurrenceID", "associatedOccurrences", "previousIdentifications", "fieldNumber", "day", "month", "year", "verbatimEventDate", "samplingProtocol", "habitat", "eventRemarks", "fieldNotes", "measurementRemarks", "continent", "country", "countryCode", "verbatimLocality", "stateProvince", "county", "municipality", "locality", "decimalLatitude", "decimalLongitude", "verbatimLatitude", "verbatimLongitude", "coordinatePrecision", "geodeticDatum", "footprintWKT", "minimumElevationInMeters", "maximumElevationInMeters", "waterBody", "minimumDepthInMeters", "maximumDepthInMeters", "locationRemarks", "identificationQualifier", "identifiedBy", "dateIdentified", "typeStatus", "scientificName", "scientificNameAuthorship", "acceptedNameUsage", "subgenus", "genus", "family", "order", "class", "phylum", "kingdom", "specificEpithet", "infraspecificEpithet", "taxonRank", "taxonomicStatus", "originalNameUsage", "vernacularName", "nomenclaturalCode", "nameAccordingTo", "relationshipOfResource", "dcterms:modified", "artificial:section", "artificial:shelfLocation", "artificial:flaskLocation", "artificial:shippingGuide", "artificial:subfamily", "artificial:subtribe", "artificial:tribe", "artificial:superfamily", "artificial:infraorder", "artificial:superorder", "artificial:suborder", "artificial:subclass", "artificial:subphylum", "dcterms:bibliographicCitation") values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"
      "bindings" => array:92 [
        0 => "nenhuma"
        1 => "PreservedSpecimen"
        2 => "UFMS"
        3 => "ZUFMS"
        4 => "material em estudo por Carla Kampião"
        5 => "ZUFMS-ACA00001"
        6 => null
        7 => "Campião, K. et al."
        8 => "93"
        9 => "animal inteiro (ETOH 70%)"
        10 => "9"
        11 => null
        12 => null
        13 => null
        14 => "selvagem"
        15 => "não informado"
        16 => "parasita de Phyllomedusa azurea (Amphibia: Hylidae)"
        17 => "em coleção"
        18 => null
        19 => null
        20 => "br:UFMS:ZUFMS:ZUFMS-ACA00001"
        21 => null
        22 => null
        23 => null
        24 => 3
        25 => 2
        26 => 2011
        27 => "03.II.2011"
        28 => null
        29 => null
        30 => null
        31 => null
        32 => null
        33 => "América do Sul"
        34 => "Brasil"
        35 => "BRA"
        36 => "Brasil"
        37 => "Mato Grosso do Sul"
        38 => "Corumbá"
        39 => ""
        40 => "Fazenda Alegria"
        41 => -18.983333
        42 => -56.65
        43 => "18°59'00"S"
        44 => "56°39'00"W"
        45 => 0.0
        46 => "WGS84"
        47 => null
        48 => 0.0
        49 => 0.0
        50 => null
        51 => 0.0
        52 => 0.0
        53 => null
        54 => null
        55 => "Campião, K."
        56 => null
        57 => null
        58 => "Acanthocephala"
        59 => null
        60 => "Acanthocephala"
        61 => null
        62 => null
        63 => null
        64 => null
        65 => null
        66 => "Acanthocephala"
        67 => "Animalia"
        68 => null
        69 => null
        70 => "filo"
        71 => null
        72 => null
        73 => null
        74 => "ICZN"
        75 => null
        76 => "nenhum"
        77 => "2017-08-30"
        78 => "Acanthocephala"
        79 => null
        80 => null
        81 => null
        82 => null
        83 => null
        84 => null
        85 => null
        86 => null
        87 => null
        88 => null
        89 => null
        90 => null
        91 => null
      ]
      "time" => 45.67
    ]
    1 => array:3 [
      "query" => "select * from "biological_occurrence" where "occurrenceID" = ? limit 1"
      "bindings" => array:1 [
        0 => "br:UFMS:ZUFMS:ZUFMS-ACA00002"
      ]
      "time" => 0.3
    ]
    2 => array:3 [
      "query" => "insert into "biological_occurrence_view" ("informationWithheld", "basisOfRecord", "institutionCode", "collectionCode", "datasetName", "catalogNumber", "otherCatalogNumbers", "recordedBy", "recordNumber", "preparations", "individualCount", "sex", "lifeStage", "reproductiveCondition", "establishmentMeans", "behavior", "occurrenceRemarks", "disposition", "associatedReferences", "associatedMedia", "occurrenceID", "associatedOccurrences", "previousIdentifications", "fieldNumber", "day", "month", "year", "verbatimEventDate", "samplingProtocol", "habitat", "eventRemarks", "fieldNotes", "measurementRemarks", "continent", "country", "countryCode", "verbatimLocality", "stateProvince", "county", "municipality", "locality", "decimalLatitude", "decimalLongitude", "verbatimLatitude", "verbatimLongitude", "coordinatePrecision", "geodeticDatum", "footprintWKT", "minimumElevationInMeters", "maximumElevationInMeters", "waterBody", "minimumDepthInMeters", "maximumDepthInMeters", "locationRemarks", "identificationQualifier", "identifiedBy", "dateIdentified", "typeStatus", "scientificName", "scientificNameAuthorship", "acceptedNameUsage", "subgenus", "genus", "family", "order", "class", "phylum", "kingdom", "specificEpithet", "infraspecificEpithet", "taxonRank", "taxonomicStatus", "originalNameUsage", "vernacularName", "nomenclaturalCode", "nameAccordingTo", "relationshipOfResource", "dcterms:modified", "artificial:section", "artificial:shelfLocation", "artificial:flaskLocation", "artificial:shippingGuide", "artificial:subfamily", "artificial:subtribe", "artificial:tribe", "artificial:superfamily", "artificial:infraorder", "artificial:superorder", "artificial:suborder", "artificial:subclass", "artificial:subphylum", "dcterms:bibliographicCitation") values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"
      "bindings" => array:92 [
        0 => "nenhuma"
        1 => "PreservedSpecimen"
        2 => "UFMS"
        3 => "ZUFMS"
        4 => "material estudado por Isabela Caroline Oliveira da Silva"
        5 => "ZUFMS-ACA00002"
        6 => null
        7 => "Silva, I. C. O."
        8 => ""
        9 => "animal inteiro (ETOH 70%)"
        10 => "1"
        11 => null
        12 => "jovem"
        13 => "não reprodutivo"
        14 => "selvagem"
        15 => "não informado"
        16 => "parasita de Pseudis paradoxa (Amphibia: Hylidae)"
        17 => "em coleção"
        18 => null
        19 => null
        20 => "br:UFMS:ZUFMS:ZUFMS-ACA00002"
        21 => null
        22 => null
        23 => null
        24 => 17
        25 => 2
        26 => 2012
        27 => "17.II.2012"
        28 => "necropsia"
        29 => "Pantanal"
        30 => null
        31 => null
        32 => null
        33 => "América do Sul"
        34 => "Brasil"
        35 => "BRA"
        36 => "Brasil"
        37 => "Mato Grosso do Sul"
        38 => "Corumbá"
        39 => ""
        40 => "Fazenda Alegria"
        41 => -18.983333
        42 => -56.65
        43 => "18°59'00"S"
        44 => "56°39'00"W"
        45 => 0.0
        46 => "WGS84"
        47 => null
        48 => 89.0
        49 => 106.0
        50 => null
        51 => 0.0
        52 => 0.0
        53 => null
        54 => null
        55 => "Silva, I. C. O."
        56 => "2016"
        57 => null
        58 => "Acanthocephala"
        59 => null
        60 => "Acanthocephala"
        61 => null
        62 => null
        63 => null
        64 => null
        65 => null
        66 => "Acanthocephala"
        67 => "Animalia"
        68 => null
        69 => null
        70 => "filo"
        71 => null
        72 => null
        73 => null
        74 => "ICZN"
        75 => null
        76 => "nenhum"
        77 => "2017-08-30"
        78 => "Acanthocephala"
        79 => null
        80 => null
        81 => null
        82 => null
        83 => null
        84 => null
        85 => null
        86 => null
        87 => null
        88 => null
        89 => null
        90 => null
        91 => null
      ]
      "time" => 15.73
    ]
  ]
  2 => array:5 [
    0 => array:3 [
      "query" => "insert into "biological_occurrence_view" ("informationWithheld", "basisOfRecord", "institutionCode", "collectionCode", "datasetName", "catalogNumber", "otherCatalogNumbers", "recordedBy", "recordNumber", "preparations", "individualCount", "sex", "lifeStage", "reproductiveCondition", "establishmentMeans", "behavior", "occurrenceRemarks", "disposition", "associatedReferences", "associatedMedia", "occurrenceID", "associatedOccurrences", "previousIdentifications", "fieldNumber", "day", "month", "year", "verbatimEventDate", "samplingProtocol", "habitat", "eventRemarks", "fieldNotes", "measurementRemarks", "continent", "country", "countryCode", "verbatimLocality", "stateProvince", "county", "municipality", "locality", "decimalLatitude", "decimalLongitude", "verbatimLatitude", "verbatimLongitude", "coordinatePrecision", "geodeticDatum", "footprintWKT", "minimumElevationInMeters", "maximumElevationInMeters", "waterBody", "minimumDepthInMeters", "maximumDepthInMeters", "locationRemarks", "identificationQualifier", "identifiedBy", "dateIdentified", "typeStatus", "scientificName", "scientificNameAuthorship", "acceptedNameUsage", "subgenus", "genus", "family", "order", "class", "phylum", "kingdom", "specificEpithet", "infraspecificEpithet", "taxonRank", "taxonomicStatus", "originalNameUsage", "vernacularName", "nomenclaturalCode", "nameAccordingTo", "relationshipOfResource", "dcterms:modified", "artificial:section", "artificial:shelfLocation", "artificial:flaskLocation", "artificial:shippingGuide", "artificial:subfamily", "artificial:subtribe", "artificial:tribe", "artificial:superfamily", "artificial:infraorder", "artificial:superorder", "artificial:suborder", "artificial:subclass", "artificial:subphylum", "dcterms:bibliographicCitation") values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"
      "bindings" => array:92 [
        0 => "nenhuma"
        1 => "PreservedSpecimen"
        2 => "UFMS"
        3 => "ZUFMS"
        4 => "material em estudo por Carla Kampião"
        5 => "ZUFMS-ACA00001"
        6 => null
        7 => "Campião, K. et al."
        8 => "93"
        9 => "animal inteiro (ETOH 70%)"
        10 => "9"
        11 => null
        12 => null
        13 => null
        14 => "selvagem"
        15 => "não informado"
        16 => "parasita de Phyllomedusa azurea (Amphibia: Hylidae)"
        17 => "em coleção"
        18 => null
        19 => null
        20 => "br:UFMS:ZUFMS:ZUFMS-ACA00001"
        21 => null
        22 => null
        23 => null
        24 => 3
        25 => 2
        26 => 2011
        27 => "03.II.2011"
        28 => null
        29 => null
        30 => null
        31 => null
        32 => null
        33 => "América do Sul"
        34 => "Brasil"
        35 => "BRA"
        36 => "Brasil"
        37 => "Mato Grosso do Sul"
        38 => "Corumbá"
        39 => ""
        40 => "Fazenda Alegria"
        41 => -18.983333
        42 => -56.65
        43 => "18°59'00"S"
        44 => "56°39'00"W"
        45 => 0.0
        46 => "WGS84"
        47 => null
        48 => 0.0
        49 => 0.0
        50 => null
        51 => 0.0
        52 => 0.0
        53 => null
        54 => null
        55 => "Campião, K."
        56 => null
        57 => null
        58 => "Acanthocephala"
        59 => null
        60 => "Acanthocephala"
        61 => null
        62 => null
        63 => null
        64 => null
        65 => null
        66 => "Acanthocephala"
        67 => "Animalia"
        68 => null
        69 => null
        70 => "filo"
        71 => null
        72 => null
        73 => null
        74 => "ICZN"
        75 => null
        76 => "nenhum"
        77 => "2017-08-30"
        78 => "Acanthocephala"
        79 => null
        80 => null
        81 => null
        82 => null
        83 => null
        84 => null
        85 => null
        86 => null
        87 => null
        88 => null
        89 => null
        90 => null
        91 => null
      ]
      "time" => 45.67
    ]
    1 => array:3 [
      "query" => "select * from "biological_occurrence" where "occurrenceID" = ? limit 1"
      "bindings" => array:1 [
        0 => "br:UFMS:ZUFMS:ZUFMS-ACA00002"
      ]
      "time" => 0.3
    ]
    2 => array:3 [
      "query" => "insert into "biological_occurrence_view" ("informationWithheld", "basisOfRecord", "institutionCode", "collectionCode", "datasetName", "catalogNumber", "otherCatalogNumbers", "recordedBy", "recordNumber", "preparations", "individualCount", "sex", "lifeStage", "reproductiveCondition", "establishmentMeans", "behavior", "occurrenceRemarks", "disposition", "associatedReferences", "associatedMedia", "occurrenceID", "associatedOccurrences", "previousIdentifications", "fieldNumber", "day", "month", "year", "verbatimEventDate", "samplingProtocol", "habitat", "eventRemarks", "fieldNotes", "measurementRemarks", "continent", "country", "countryCode", "verbatimLocality", "stateProvince", "county", "municipality", "locality", "decimalLatitude", "decimalLongitude", "verbatimLatitude", "verbatimLongitude", "coordinatePrecision", "geodeticDatum", "footprintWKT", "minimumElevationInMeters", "maximumElevationInMeters", "waterBody", "minimumDepthInMeters", "maximumDepthInMeters", "locationRemarks", "identificationQualifier", "identifiedBy", "dateIdentified", "typeStatus", "scientificName", "scientificNameAuthorship", "acceptedNameUsage", "subgenus", "genus", "family", "order", "class", "phylum", "kingdom", "specificEpithet", "infraspecificEpithet", "taxonRank", "taxonomicStatus", "originalNameUsage", "vernacularName", "nomenclaturalCode", "nameAccordingTo", "relationshipOfResource", "dcterms:modified", "artificial:section", "artificial:shelfLocation", "artificial:flaskLocation", "artificial:shippingGuide", "artificial:subfamily", "artificial:subtribe", "artificial:tribe", "artificial:superfamily", "artificial:infraorder", "artificial:superorder", "artificial:suborder", "artificial:subclass", "artificial:subphylum", "dcterms:bibliographicCitation") values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"
      "bindings" => array:92 [
        0 => "nenhuma"
        1 => "PreservedSpecimen"
        2 => "UFMS"
        3 => "ZUFMS"
        4 => "material estudado por Isabela Caroline Oliveira da Silva"
        5 => "ZUFMS-ACA00002"
        6 => null
        7 => "Silva, I. C. O."
        8 => ""
        9 => "animal inteiro (ETOH 70%)"
        10 => "1"
        11 => null
        12 => "jovem"
        13 => "não reprodutivo"
        14 => "selvagem"
        15 => "não informado"
        16 => "parasita de Pseudis paradoxa (Amphibia: Hylidae)"
        17 => "em coleção"
        18 => null
        19 => null
        20 => "br:UFMS:ZUFMS:ZUFMS-ACA00002"
        21 => null
        22 => null
        23 => null
        24 => 17
        25 => 2
        26 => 2012
        27 => "17.II.2012"
        28 => "necropsia"
        29 => "Pantanal"
        30 => null
        31 => null
        32 => null
        33 => "América do Sul"
        34 => "Brasil"
        35 => "BRA"
        36 => "Brasil"
        37 => "Mato Grosso do Sul"
        38 => "Corumbá"
        39 => ""
        40 => "Fazenda Alegria"
        41 => -18.983333
        42 => -56.65
        43 => "18°59'00"S"
        44 => "56°39'00"W"
        45 => 0.0
        46 => "WGS84"
        47 => null
        48 => 89.0
        49 => 106.0
        50 => null
        51 => 0.0
        52 => 0.0
        53 => null
        54 => null
        55 => "Silva, I. C. O."
        56 => "2016"
        57 => null
        58 => "Acanthocephala"
        59 => null
        60 => "Acanthocephala"
        61 => null
        62 => null
        63 => null
        64 => null
        65 => null
        66 => "Acanthocephala"
        67 => "Animalia"
        68 => null
        69 => null
        70 => "filo"
        71 => null
        72 => null
        73 => null
        74 => "ICZN"
        75 => null
        76 => "nenhum"
        77 => "2017-08-30"
        78 => "Acanthocephala"
        79 => null
        80 => null
        81 => null
        82 => null
        83 => null
        84 => null
        85 => null
        86 => null
        87 => null
        88 => null
        89 => null
        90 => null
        91 => null
      ]
      "time" => 15.73
    ]
    3 => array:3 [
      "query" => "select * from "biological_occurrence" where "occurrenceID" = ? limit 1"
      "bindings" => array:1 [
        0 => "br:UFMS:ZUFMS:ZUFMS-ACA00003"
      ]
      "time" => 0.52
    ]
    4 => array:3 [
      "query" => "insert into "biological_occurrence_view" ("informationWithheld", "basisOfRecord", "institutionCode", "collectionCode", "datasetName", "catalogNumber", "otherCatalogNumbers", "recordedBy", "recordNumber", "preparations", "individualCount", "sex", "lifeStage", "reproductiveCondition", "establishmentMeans", "behavior", "occurrenceRemarks", "disposition", "associatedReferences", "associatedMedia", "occurrenceID", "associatedOccurrences", "previousIdentifications", "fieldNumber", "day", "month", "year", "verbatimEventDate", "samplingProtocol", "habitat", "eventRemarks", "fieldNotes", "measurementRemarks", "continent", "country", "countryCode", "verbatimLocality", "stateProvince", "county", "municipality", "locality", "decimalLatitude", "decimalLongitude", "verbatimLatitude", "verbatimLongitude", "coordinatePrecision", "geodeticDatum", "footprintWKT", "minimumElevationInMeters", "maximumElevationInMeters", "waterBody", "minimumDepthInMeters", "maximumDepthInMeters", "locationRemarks", "identificationQualifier", "identifiedBy", "dateIdentified", "typeStatus", "scientificName", "scientificNameAuthorship", "acceptedNameUsage", "subgenus", "genus", "family", "order", "class", "phylum", "kingdom", "specificEpithet", "infraspecificEpithet", "taxonRank", "taxonomicStatus", "originalNameUsage", "vernacularName", "nomenclaturalCode", "nameAccordingTo", "relationshipOfResource", "dcterms:modified", "artificial:section", "artificial:shelfLocation", "artificial:flaskLocation", "artificial:shippingGuide", "artificial:subfamily", "artificial:subtribe", "artificial:tribe", "artificial:superfamily", "artificial:infraorder", "artificial:superorder", "artificial:suborder", "artificial:subclass", "artificial:subphylum", "dcterms:bibliographicCitation") values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"
      "bindings" => array:92 [
        0 => "nenhuma"
        1 => "PreservedSpecimen"
        2 => "UFMS"
        3 => "ZUFMS"
        4 => "Laboratório de Parasitologia Animal; Doutorado Isabela Caroline Oliveira da Silva"
        5 => "ZUFMS-ACA00003"
        6 => null
        7 => "SILVA, I. C. O."
        8 => "206"
        9 => "animal inteiro (ETOH 70%)"
        10 => "1"
        11 => null
        12 => "adulto"
        13 => "indeterminado"
        14 => "selvagem"
        15 => "parasitando"
        16 => "não informado"
        17 => "em tombamento"
        18 => null
        19 => null
        20 => "br:UFMS:ZUFMS:ZUFMS-ACA00003"
        21 => null
        22 => null
        23 => null
        24 => 26
        25 => 1
        26 => 2019
        27 => "26.I.2019"
        28 => "necropsia"
        29 => "Cerrado"
        30 => null
        31 => null
        32 => "não informado"
        33 => "América do Sul"
        34 => "Brasil"
        35 => "BRA"
        36 => "Brasil"
        37 => "Mato Grosso do Sul"
        38 => "Alcinópolis"
        39 => ""
        40 => "Parque Estadual das Nascentes do Rio Taquari"
        41 => -18.165139
        42 => -53.415806
        43 => "18°09'54.5"S"
        44 => "53°24'56.9"W"
        45 => 0.0
        46 => "WGS84"
        47 => null
        48 => 0.0
        49 => 0.0
        50 => null
        51 => 0.0
        52 => 0.0
        53 => null
        54 => null
        55 => "SILVA, I. C. O."
        56 => "2020-09-23"
        57 => "voucher"
        58 => "Centrorhynchidae"
        59 => "Van Cleave, 1916"
        60 => "Centrorhynchidae Van Cleave, 1916"
        61 => null
        62 => null
        63 => "Centrorhynchidae"
        64 => "Polymorphida"
        65 => "Palaeacanthocephala"
        66 => "Acanthocephala"
        67 => "Animalia"
        68 => null
        69 => null
        70 => "família"
        71 => "aceito"
        72 => null
        73 => null
        74 => "ICZN"
        75 => "NCBI, 2021"
        76 => "nenhum"
        77 => "2021-07-15"
        78 => "Acanthocephala"
        79 => null
        80 => null
        81 => null
        82 => null
        83 => null
        84 => null
        85 => null
        86 => null
        87 => null
        88 => null
        89 => null
        90 => null
        91 => null
      ]
      "time" => 17.19
    ]
  ]
  3 => array:7 [
    0 => array:3 [
      "query" => "insert into "biological_occurrence_view" ("informationWithheld", "basisOfRecord", "institutionCode", "collectionCode", "datasetName", "catalogNumber", "otherCatalogNumbers", "recordedBy", "recordNumber", "preparations", "individualCount", "sex", "lifeStage", "reproductiveCondition", "establishmentMeans", "behavior", "occurrenceRemarks", "disposition", "associatedReferences", "associatedMedia", "occurrenceID", "associatedOccurrences", "previousIdentifications", "fieldNumber", "day", "month", "year", "verbatimEventDate", "samplingProtocol", "habitat", "eventRemarks", "fieldNotes", "measurementRemarks", "continent", "country", "countryCode", "verbatimLocality", "stateProvince", "county", "municipality", "locality", "decimalLatitude", "decimalLongitude", "verbatimLatitude", "verbatimLongitude", "coordinatePrecision", "geodeticDatum", "footprintWKT", "minimumElevationInMeters", "maximumElevationInMeters", "waterBody", "minimumDepthInMeters", "maximumDepthInMeters", "locationRemarks", "identificationQualifier", "identifiedBy", "dateIdentified", "typeStatus", "scientificName", "scientificNameAuthorship", "acceptedNameUsage", "subgenus", "genus", "family", "order", "class", "phylum", "kingdom", "specificEpithet", "infraspecificEpithet", "taxonRank", "taxonomicStatus", "originalNameUsage", "vernacularName", "nomenclaturalCode", "nameAccordingTo", "relationshipOfResource", "dcterms:modified", "artificial:section", "artificial:shelfLocation", "artificial:flaskLocation", "artificial:shippingGuide", "artificial:subfamily", "artificial:subtribe", "artificial:tribe", "artificial:superfamily", "artificial:infraorder", "artificial:superorder", "artificial:suborder", "artificial:subclass", "artificial:subphylum", "dcterms:bibliographicCitation") values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"
      "bindings" => array:92 [
        0 => "nenhuma"
        1 => "PreservedSpecimen"
        2 => "UFMS"
        3 => "ZUFMS"
        4 => "material em estudo por Carla Kampião"
        5 => "ZUFMS-ACA00001"
        6 => null
        7 => "Campião, K. et al."
        8 => "93"
        9 => "animal inteiro (ETOH 70%)"
        10 => "9"
        11 => null
        12 => null
        13 => null
        14 => "selvagem"
        15 => "não informado"
        16 => "parasita de Phyllomedusa azurea (Amphibia: Hylidae)"
        17 => "em coleção"
        18 => null
        19 => null
        20 => "br:UFMS:ZUFMS:ZUFMS-ACA00001"
        21 => null
        22 => null
        23 => null
        24 => 3
        25 => 2
        26 => 2011
        27 => "03.II.2011"
        28 => null
        29 => null
        30 => null
        31 => null
        32 => null
        33 => "América do Sul"
        34 => "Brasil"
        35 => "BRA"
        36 => "Brasil"
        37 => "Mato Grosso do Sul"
        38 => "Corumbá"
        39 => ""
        40 => "Fazenda Alegria"
        41 => -18.983333
        42 => -56.65
        43 => "18°59'00"S"
        44 => "56°39'00"W"
        45 => 0.0
        46 => "WGS84"
        47 => null
        48 => 0.0
        49 => 0.0
        50 => null
        51 => 0.0
        52 => 0.0
        53 => null
        54 => null
        55 => "Campião, K."
        56 => null
        57 => null
        58 => "Acanthocephala"
        59 => null
        60 => "Acanthocephala"
        61 => null
        62 => null
        63 => null
        64 => null
        65 => null
        66 => "Acanthocephala"
        67 => "Animalia"
        68 => null
        69 => null
        70 => "filo"
        71 => null
        72 => null
        73 => null
        74 => "ICZN"
        75 => null
        76 => "nenhum"
        77 => "2017-08-30"
        78 => "Acanthocephala"
        79 => null
        80 => null
        81 => null
        82 => null
        83 => null
        84 => null
        85 => null
        86 => null
        87 => null
        88 => null
        89 => null
        90 => null
        91 => null
      ]
      "time" => 45.67
    ]
    1 => array:3 [
      "query" => "select * from "biological_occurrence" where "occurrenceID" = ? limit 1"
      "bindings" => array:1 [
        0 => "br:UFMS:ZUFMS:ZUFMS-ACA00002"
      ]
      "time" => 0.3
    ]
    2 => array:3 [
      "query" => "insert into "biological_occurrence_view" ("informationWithheld", "basisOfRecord", "institutionCode", "collectionCode", "datasetName", "catalogNumber", "otherCatalogNumbers", "recordedBy", "recordNumber", "preparations", "individualCount", "sex", "lifeStage", "reproductiveCondition", "establishmentMeans", "behavior", "occurrenceRemarks", "disposition", "associatedReferences", "associatedMedia", "occurrenceID", "associatedOccurrences", "previousIdentifications", "fieldNumber", "day", "month", "year", "verbatimEventDate", "samplingProtocol", "habitat", "eventRemarks", "fieldNotes", "measurementRemarks", "continent", "country", "countryCode", "verbatimLocality", "stateProvince", "county", "municipality", "locality", "decimalLatitude", "decimalLongitude", "verbatimLatitude", "verbatimLongitude", "coordinatePrecision", "geodeticDatum", "footprintWKT", "minimumElevationInMeters", "maximumElevationInMeters", "waterBody", "minimumDepthInMeters", "maximumDepthInMeters", "locationRemarks", "identificationQualifier", "identifiedBy", "dateIdentified", "typeStatus", "scientificName", "scientificNameAuthorship", "acceptedNameUsage", "subgenus", "genus", "family", "order", "class", "phylum", "kingdom", "specificEpithet", "infraspecificEpithet", "taxonRank", "taxonomicStatus", "originalNameUsage", "vernacularName", "nomenclaturalCode", "nameAccordingTo", "relationshipOfResource", "dcterms:modified", "artificial:section", "artificial:shelfLocation", "artificial:flaskLocation", "artificial:shippingGuide", "artificial:subfamily", "artificial:subtribe", "artificial:tribe", "artificial:superfamily", "artificial:infraorder", "artificial:superorder", "artificial:suborder", "artificial:subclass", "artificial:subphylum", "dcterms:bibliographicCitation") values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"
      "bindings" => array:92 [
        0 => "nenhuma"
        1 => "PreservedSpecimen"
        2 => "UFMS"
        3 => "ZUFMS"
        4 => "material estudado por Isabela Caroline Oliveira da Silva"
        5 => "ZUFMS-ACA00002"
        6 => null
        7 => "Silva, I. C. O."
        8 => ""
        9 => "animal inteiro (ETOH 70%)"
        10 => "1"
        11 => null
        12 => "jovem"
        13 => "não reprodutivo"
        14 => "selvagem"
        15 => "não informado"
        16 => "parasita de Pseudis paradoxa (Amphibia: Hylidae)"
        17 => "em coleção"
        18 => null
        19 => null
        20 => "br:UFMS:ZUFMS:ZUFMS-ACA00002"
        21 => null
        22 => null
        23 => null
        24 => 17
        25 => 2
        26 => 2012
        27 => "17.II.2012"
        28 => "necropsia"
        29 => "Pantanal"
        30 => null
        31 => null
        32 => null
        33 => "América do Sul"
        34 => "Brasil"
        35 => "BRA"
        36 => "Brasil"
        37 => "Mato Grosso do Sul"
        38 => "Corumbá"
        39 => ""
        40 => "Fazenda Alegria"
        41 => -18.983333
        42 => -56.65
        43 => "18°59'00"S"
        44 => "56°39'00"W"
        45 => 0.0
        46 => "WGS84"
        47 => null
        48 => 89.0
        49 => 106.0
        50 => null
        51 => 0.0
        52 => 0.0
        53 => null
        54 => null
        55 => "Silva, I. C. O."
        56 => "2016"
        57 => null
        58 => "Acanthocephala"
        59 => null
        60 => "Acanthocephala"
        61 => null
        62 => null
        63 => null
        64 => null
        65 => null
        66 => "Acanthocephala"
        67 => "Animalia"
        68 => null
        69 => null
        70 => "filo"
        71 => null
        72 => null
        73 => null
        74 => "ICZN"
        75 => null
        76 => "nenhum"
        77 => "2017-08-30"
        78 => "Acanthocephala"
        79 => null
        80 => null
        81 => null
        82 => null
        83 => null
        84 => null
        85 => null
        86 => null
        87 => null
        88 => null
        89 => null
        90 => null
        91 => null
      ]
      "time" => 15.73
    ]
    3 => array:3 [
      "query" => "select * from "biological_occurrence" where "occurrenceID" = ? limit 1"
      "bindings" => array:1 [
        0 => "br:UFMS:ZUFMS:ZUFMS-ACA00003"
      ]
      "time" => 0.52
    ]
    4 => array:3 [
      "query" => "insert into "biological_occurrence_view" ("informationWithheld", "basisOfRecord", "institutionCode", "collectionCode", "datasetName", "catalogNumber", "otherCatalogNumbers", "recordedBy", "recordNumber", "preparations", "individualCount", "sex", "lifeStage", "reproductiveCondition", "establishmentMeans", "behavior", "occurrenceRemarks", "disposition", "associatedReferences", "associatedMedia", "occurrenceID", "associatedOccurrences", "previousIdentifications", "fieldNumber", "day", "month", "year", "verbatimEventDate", "samplingProtocol", "habitat", "eventRemarks", "fieldNotes", "measurementRemarks", "continent", "country", "countryCode", "verbatimLocality", "stateProvince", "county", "municipality", "locality", "decimalLatitude", "decimalLongitude", "verbatimLatitude", "verbatimLongitude", "coordinatePrecision", "geodeticDatum", "footprintWKT", "minimumElevationInMeters", "maximumElevationInMeters", "waterBody", "minimumDepthInMeters", "maximumDepthInMeters", "locationRemarks", "identificationQualifier", "identifiedBy", "dateIdentified", "typeStatus", "scientificName", "scientificNameAuthorship", "acceptedNameUsage", "subgenus", "genus", "family", "order", "class", "phylum", "kingdom", "specificEpithet", "infraspecificEpithet", "taxonRank", "taxonomicStatus", "originalNameUsage", "vernacularName", "nomenclaturalCode", "nameAccordingTo", "relationshipOfResource", "dcterms:modified", "artificial:section", "artificial:shelfLocation", "artificial:flaskLocation", "artificial:shippingGuide", "artificial:subfamily", "artificial:subtribe", "artificial:tribe", "artificial:superfamily", "artificial:infraorder", "artificial:superorder", "artificial:suborder", "artificial:subclass", "artificial:subphylum", "dcterms:bibliographicCitation") values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"
      "bindings" => array:92 [
        0 => "nenhuma"
        1 => "PreservedSpecimen"
        2 => "UFMS"
        3 => "ZUFMS"
        4 => "Laboratório de Parasitologia Animal; Doutorado Isabela Caroline Oliveira da Silva"
        5 => "ZUFMS-ACA00003"
        6 => null
        7 => "SILVA, I. C. O."
        8 => "206"
        9 => "animal inteiro (ETOH 70%)"
        10 => "1"
        11 => null
        12 => "adulto"
        13 => "indeterminado"
        14 => "selvagem"
        15 => "parasitando"
        16 => "não informado"
        17 => "em tombamento"
        18 => null
        19 => null
        20 => "br:UFMS:ZUFMS:ZUFMS-ACA00003"
        21 => null
        22 => null
        23 => null
        24 => 26
        25 => 1
        26 => 2019
        27 => "26.I.2019"
        28 => "necropsia"
        29 => "Cerrado"
        30 => null
        31 => null
        32 => "não informado"
        33 => "América do Sul"
        34 => "Brasil"
        35 => "BRA"
        36 => "Brasil"
        37 => "Mato Grosso do Sul"
        38 => "Alcinópolis"
        39 => ""
        40 => "Parque Estadual das Nascentes do Rio Taquari"
        41 => -18.165139
        42 => -53.415806
        43 => "18°09'54.5"S"
        44 => "53°24'56.9"W"
        45 => 0.0
        46 => "WGS84"
        47 => null
        48 => 0.0
        49 => 0.0
        50 => null
        51 => 0.0
        52 => 0.0
        53 => null
        54 => null
        55 => "SILVA, I. C. O."
        56 => "2020-09-23"
        57 => "voucher"
        58 => "Centrorhynchidae"
        59 => "Van Cleave, 1916"
        60 => "Centrorhynchidae Van Cleave, 1916"
        61 => null
        62 => null
        63 => "Centrorhynchidae"
        64 => "Polymorphida"
        65 => "Palaeacanthocephala"
        66 => "Acanthocephala"
        67 => "Animalia"
        68 => null
        69 => null
        70 => "família"
        71 => "aceito"
        72 => null
        73 => null
        74 => "ICZN"
        75 => "NCBI, 2021"
        76 => "nenhum"
        77 => "2021-07-15"
        78 => "Acanthocephala"
        79 => null
        80 => null
        81 => null
        82 => null
        83 => null
        84 => null
        85 => null
        86 => null
        87 => null
        88 => null
        89 => null
        90 => null
        91 => null
      ]
      "time" => 17.19
    ]
    5 => array:3 [
      "query" => "select * from "biological_occurrence" where "occurrenceID" = ? limit 1"
      "bindings" => array:1 [
        0 => "br:UFMS:ZUFMS:ZUFMS-ACA00004"
      ]
      "time" => 0.65
    ]
    6 => array:3 [
      "query" => "insert into "biological_occurrence_view" ("informationWithheld", "basisOfRecord", "institutionCode", "collectionCode", "datasetName", "catalogNumber", "otherCatalogNumbers", "recordedBy", "recordNumber", "preparations", "individualCount", "sex", "lifeStage", "reproductiveCondition", "establishmentMeans", "behavior", "occurrenceRemarks", "disposition", "associatedReferences", "associatedMedia", "occurrenceID", "associatedOccurrences", "previousIdentifications", "fieldNumber", "day", "month", "year", "verbatimEventDate", "samplingProtocol", "habitat", "eventRemarks", "fieldNotes", "measurementRemarks", "continent", "country", "countryCode", "verbatimLocality", "stateProvince", "county", "municipality", "locality", "decimalLatitude", "decimalLongitude", "verbatimLatitude", "verbatimLongitude", "coordinatePrecision", "geodeticDatum", "footprintWKT", "minimumElevationInMeters", "maximumElevationInMeters", "waterBody", "minimumDepthInMeters", "maximumDepthInMeters", "locationRemarks", "identificationQualifier", "identifiedBy", "dateIdentified", "typeStatus", "scientificName", "scientificNameAuthorship", "acceptedNameUsage", "subgenus", "genus", "family", "order", "class", "phylum", "kingdom", "specificEpithet", "infraspecificEpithet", "taxonRank", "taxonomicStatus", "originalNameUsage", "vernacularName", "nomenclaturalCode", "nameAccordingTo", "relationshipOfResource", "dcterms:modified", "artificial:section", "artificial:shelfLocation", "artificial:flaskLocation", "artificial:shippingGuide", "artificial:subfamily", "artificial:subtribe", "artificial:tribe", "artificial:superfamily", "artificial:infraorder", "artificial:superorder", "artificial:suborder", "artificial:subclass", "artificial:subphylum", "dcterms:bibliographicCitation") values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"
      "bindings" => array:92 [
        0 => "nenhuma"
        1 => "PreservedSpecimen"
        2 => "UFMS"
        3 => "ZUFMS"
        4 => "Laboratório de Parasitologia Animal; Doutorado Isabela Caroline Oliveira da Silva"
        5 => "ZUFMS-ACA00004"
        6 => null
        7 => "SILVA, I. C. O."
        8 => "208"
        9 => "animal inteiro (ETOH 70%)"
        10 => "1"
        11 => null
        12 => "adulto"
        13 => "não reprodutivo"
        14 => "selvagem"
        15 => "parasitando"
        16 => "não informado"
        17 => "em tombamento"
        18 => null
        19 => null
        20 => "br:UFMS:ZUFMS:ZUFMS-ACA00004"
        21 => null
        22 => null
        23 => null
        24 => 27
        25 => 1
        26 => 2019
        27 => "27.I.2019"
        28 => "necropsia"
        29 => "Cerrado"
        30 => null
        31 => null
        32 => "não informado"
        33 => "América do Sul"
        34 => "Brasil"
        35 => "BRA"
        36 => "Brasil"
        37 => "Mato Grosso do Sul"
        38 => "Alcinópolis"
        39 => ""
        40 => "Parque Estadual das Nascentes do Rio Taquari"
        41 => -18.165139
        42 => -53.415806
        43 => "18°09'54.5"S"
        44 => "53°24'56.9"W"
        45 => 0.0
        46 => "WGS84"
        47 => null
        48 => 0.0
        49 => 0.0
        50 => null
        51 => 0.0
        52 => 0.0
        53 => null
        54 => "sp."
        55 => "SILVA, I. C. O."
        56 => "2020-09-23"
        57 => "voucher"
        58 => "Oligacanthorhynchus"
        59 => "Travassos, 1915"
        60 => "Oligacanthorhynchus sp. Travassos, 1915"
        61 => null
        62 => "Oligacanthorhynchus"
        63 => "Oligacanthorhynchidae"
        64 => "Oligacanthorhynchida"
        65 => "Archiacanthocephala"
        66 => "Acanthocephala"
        67 => "Animalia"
        68 => null
        69 => null
        70 => "gênero"
        71 => "aceito"
        72 => null
        73 => null
        74 => "ICZN"
        75 => "NCBI, 2021"
        76 => "nenhum"
        77 => "2021-07-15"
        78 => "Acanthocephala"
        79 => null
        80 => null
        81 => null
        82 => null
        83 => null
        84 => null
        85 => null
        86 => null
        87 => null
        88 => null
        89 => null
        90 => null
        91 => null
      ]
      "time" => 15.13
    ]
  ]
  4 => array:9 [
    0 => array:3 [
      "query" => "insert into "biological_occurrence_view" ("informationWithheld", "basisOfRecord", "institutionCode", "collectionCode", "datasetName", "catalogNumber", "otherCatalogNumbers", "recordedBy", "recordNumber", "preparations", "individualCount", "sex", "lifeStage", "reproductiveCondition", "establishmentMeans", "behavior", "occurrenceRemarks", "disposition", "associatedReferences", "associatedMedia", "occurrenceID", "associatedOccurrences", "previousIdentifications", "fieldNumber", "day", "month", "year", "verbatimEventDate", "samplingProtocol", "habitat", "eventRemarks", "fieldNotes", "measurementRemarks", "continent", "country", "countryCode", "verbatimLocality", "stateProvince", "county", "municipality", "locality", "decimalLatitude", "decimalLongitude", "verbatimLatitude", "verbatimLongitude", "coordinatePrecision", "geodeticDatum", "footprintWKT", "minimumElevationInMeters", "maximumElevationInMeters", "waterBody", "minimumDepthInMeters", "maximumDepthInMeters", "locationRemarks", "identificationQualifier", "identifiedBy", "dateIdentified", "typeStatus", "scientificName", "scientificNameAuthorship", "acceptedNameUsage", "subgenus", "genus", "family", "order", "class", "phylum", "kingdom", "specificEpithet", "infraspecificEpithet", "taxonRank", "taxonomicStatus", "originalNameUsage", "vernacularName", "nomenclaturalCode", "nameAccordingTo", "relationshipOfResource", "dcterms:modified", "artificial:section", "artificial:shelfLocation", "artificial:flaskLocation", "artificial:shippingGuide", "artificial:subfamily", "artificial:subtribe", "artificial:tribe", "artificial:superfamily", "artificial:infraorder", "artificial:superorder", "artificial:suborder", "artificial:subclass", "artificial:subphylum", "dcterms:bibliographicCitation") values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"
      "bindings" => array:92 [
        0 => "nenhuma"
        1 => "PreservedSpecimen"
        2 => "UFMS"
        3 => "ZUFMS"
        4 => "material em estudo por Carla Kampião"
        5 => "ZUFMS-ACA00001"
        6 => null
        7 => "Campião, K. et al."
        8 => "93"
        9 => "animal inteiro (ETOH 70%)"
        10 => "9"
        11 => null
        12 => null
        13 => null
        14 => "selvagem"
        15 => "não informado"
        16 => "parasita de Phyllomedusa azurea (Amphibia: Hylidae)"
        17 => "em coleção"
        18 => null
        19 => null
        20 => "br:UFMS:ZUFMS:ZUFMS-ACA00001"
        21 => null
        22 => null
        23 => null
        24 => 3
        25 => 2
        26 => 2011
        27 => "03.II.2011"
        28 => null
        29 => null
        30 => null
        31 => null
        32 => null
        33 => "América do Sul"
        34 => "Brasil"
        35 => "BRA"
        36 => "Brasil"
        37 => "Mato Grosso do Sul"
        38 => "Corumbá"
        39 => ""
        40 => "Fazenda Alegria"
        41 => -18.983333
        42 => -56.65
        43 => "18°59'00"S"
        44 => "56°39'00"W"
        45 => 0.0
        46 => "WGS84"
        47 => null
        48 => 0.0
        49 => 0.0
        50 => null
        51 => 0.0
        52 => 0.0
        53 => null
        54 => null
        55 => "Campião, K."
        56 => null
        57 => null
        58 => "Acanthocephala"
        59 => null
        60 => "Acanthocephala"
        61 => null
        62 => null
        63 => null
        64 => null
        65 => null
        66 => "Acanthocephala"
        67 => "Animalia"
        68 => null
        69 => null
        70 => "filo"
        71 => null
        72 => null
        73 => null
        74 => "ICZN"
        75 => null
        76 => "nenhum"
        77 => "2017-08-30"
        78 => "Acanthocephala"
        79 => null
        80 => null
        81 => null
        82 => null
        83 => null
        84 => null
        85 => null
        86 => null
        87 => null
        88 => null
        89 => null
        90 => null
        91 => null
      ]
      "time" => 45.67
    ]
    1 => array:3 [
      "query" => "select * from "biological_occurrence" where "occurrenceID" = ? limit 1"
      "bindings" => array:1 [
        0 => "br:UFMS:ZUFMS:ZUFMS-ACA00002"
      ]
      "time" => 0.3
    ]
    2 => array:3 [
      "query" => "insert into "biological_occurrence_view" ("informationWithheld", "basisOfRecord", "institutionCode", "collectionCode", "datasetName", "catalogNumber", "otherCatalogNumbers", "recordedBy", "recordNumber", "preparations", "individualCount", "sex", "lifeStage", "reproductiveCondition", "establishmentMeans", "behavior", "occurrenceRemarks", "disposition", "associatedReferences", "associatedMedia", "occurrenceID", "associatedOccurrences", "previousIdentifications", "fieldNumber", "day", "month", "year", "verbatimEventDate", "samplingProtocol", "habitat", "eventRemarks", "fieldNotes", "measurementRemarks", "continent", "country", "countryCode", "verbatimLocality", "stateProvince", "county", "municipality", "locality", "decimalLatitude", "decimalLongitude", "verbatimLatitude", "verbatimLongitude", "coordinatePrecision", "geodeticDatum", "footprintWKT", "minimumElevationInMeters", "maximumElevationInMeters", "waterBody", "minimumDepthInMeters", "maximumDepthInMeters", "locationRemarks", "identificationQualifier", "identifiedBy", "dateIdentified", "typeStatus", "scientificName", "scientificNameAuthorship", "acceptedNameUsage", "subgenus", "genus", "family", "order", "class", "phylum", "kingdom", "specificEpithet", "infraspecificEpithet", "taxonRank", "taxonomicStatus", "originalNameUsage", "vernacularName", "nomenclaturalCode", "nameAccordingTo", "relationshipOfResource", "dcterms:modified", "artificial:section", "artificial:shelfLocation", "artificial:flaskLocation", "artificial:shippingGuide", "artificial:subfamily", "artificial:subtribe", "artificial:tribe", "artificial:superfamily", "artificial:infraorder", "artificial:superorder", "artificial:suborder", "artificial:subclass", "artificial:subphylum", "dcterms:bibliographicCitation") values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"
      "bindings" => array:92 [
        0 => "nenhuma"
        1 => "PreservedSpecimen"
        2 => "UFMS"
        3 => "ZUFMS"
        4 => "material estudado por Isabela Caroline Oliveira da Silva"
        5 => "ZUFMS-ACA00002"
        6 => null
        7 => "Silva, I. C. O."
        8 => ""
        9 => "animal inteiro (ETOH 70%)"
        10 => "1"
        11 => null
        12 => "jovem"
        13 => "não reprodutivo"
        14 => "selvagem"
        15 => "não informado"
        16 => "parasita de Pseudis paradoxa (Amphibia: Hylidae)"
        17 => "em coleção"
        18 => null
        19 => null
        20 => "br:UFMS:ZUFMS:ZUFMS-ACA00002"
        21 => null
        22 => null
        23 => null
        24 => 17
        25 => 2
        26 => 2012
        27 => "17.II.2012"
        28 => "necropsia"
        29 => "Pantanal"
        30 => null
        31 => null
        32 => null
        33 => "América do Sul"
        34 => "Brasil"
        35 => "BRA"
        36 => "Brasil"
        37 => "Mato Grosso do Sul"
        38 => "Corumbá"
        39 => ""
        40 => "Fazenda Alegria"
        41 => -18.983333
        42 => -56.65
        43 => "18°59'00"S"
        44 => "56°39'00"W"
        45 => 0.0
        46 => "WGS84"
        47 => null
        48 => 89.0
        49 => 106.0
        50 => null
        51 => 0.0
        52 => 0.0
        53 => null
        54 => null
        55 => "Silva, I. C. O."
        56 => "2016"
        57 => null
        58 => "Acanthocephala"
        59 => null
        60 => "Acanthocephala"
        61 => null
        62 => null
        63 => null
        64 => null
        65 => null
        66 => "Acanthocephala"
        67 => "Animalia"
        68 => null
        69 => null
        70 => "filo"
        71 => null
        72 => null
        73 => null
        74 => "ICZN"
        75 => null
        76 => "nenhum"
        77 => "2017-08-30"
        78 => "Acanthocephala"
        79 => null
        80 => null
        81 => null
        82 => null
        83 => null
        84 => null
        85 => null
        86 => null
        87 => null
        88 => null
        89 => null
        90 => null
        91 => null
      ]
      "time" => 15.73
    ]
    3 => array:3 [
      "query" => "select * from "biological_occurrence" where "occurrenceID" = ? limit 1"
      "bindings" => array:1 [
        0 => "br:UFMS:ZUFMS:ZUFMS-ACA00003"
      ]
      "time" => 0.52
    ]
    4 => array:3 [
      "query" => "insert into "biological_occurrence_view" ("informationWithheld", "basisOfRecord", "institutionCode", "collectionCode", "datasetName", "catalogNumber", "otherCatalogNumbers", "recordedBy", "recordNumber", "preparations", "individualCount", "sex", "lifeStage", "reproductiveCondition", "establishmentMeans", "behavior", "occurrenceRemarks", "disposition", "associatedReferences", "associatedMedia", "occurrenceID", "associatedOccurrences", "previousIdentifications", "fieldNumber", "day", "month", "year", "verbatimEventDate", "samplingProtocol", "habitat", "eventRemarks", "fieldNotes", "measurementRemarks", "continent", "country", "countryCode", "verbatimLocality", "stateProvince", "county", "municipality", "locality", "decimalLatitude", "decimalLongitude", "verbatimLatitude", "verbatimLongitude", "coordinatePrecision", "geodeticDatum", "footprintWKT", "minimumElevationInMeters", "maximumElevationInMeters", "waterBody", "minimumDepthInMeters", "maximumDepthInMeters", "locationRemarks", "identificationQualifier", "identifiedBy", "dateIdentified", "typeStatus", "scientificName", "scientificNameAuthorship", "acceptedNameUsage", "subgenus", "genus", "family", "order", "class", "phylum", "kingdom", "specificEpithet", "infraspecificEpithet", "taxonRank", "taxonomicStatus", "originalNameUsage", "vernacularName", "nomenclaturalCode", "nameAccordingTo", "relationshipOfResource", "dcterms:modified", "artificial:section", "artificial:shelfLocation", "artificial:flaskLocation", "artificial:shippingGuide", "artificial:subfamily", "artificial:subtribe", "artificial:tribe", "artificial:superfamily", "artificial:infraorder", "artificial:superorder", "artificial:suborder", "artificial:subclass", "artificial:subphylum", "dcterms:bibliographicCitation") values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"
      "bindings" => array:92 [
        0 => "nenhuma"
        1 => "PreservedSpecimen"
        2 => "UFMS"
        3 => "ZUFMS"
        4 => "Laboratório de Parasitologia Animal; Doutorado Isabela Caroline Oliveira da Silva"
        5 => "ZUFMS-ACA00003"
        6 => null
        7 => "SILVA, I. C. O."
        8 => "206"
        9 => "animal inteiro (ETOH 70%)"
        10 => "1"
        11 => null
        12 => "adulto"
        13 => "indeterminado"
        14 => "selvagem"
        15 => "parasitando"
        16 => "não informado"
        17 => "em tombamento"
        18 => null
        19 => null
        20 => "br:UFMS:ZUFMS:ZUFMS-ACA00003"
        21 => null
        22 => null
        23 => null
        24 => 26
        25 => 1
        26 => 2019
        27 => "26.I.2019"
        28 => "necropsia"
        29 => "Cerrado"
        30 => null
        31 => null
        32 => "não informado"
        33 => "América do Sul"
        34 => "Brasil"
        35 => "BRA"
        36 => "Brasil"
        37 => "Mato Grosso do Sul"
        38 => "Alcinópolis"
        39 => ""
        40 => "Parque Estadual das Nascentes do Rio Taquari"
        41 => -18.165139
        42 => -53.415806
        43 => "18°09'54.5"S"
        44 => "53°24'56.9"W"
        45 => 0.0
        46 => "WGS84"
        47 => null
        48 => 0.0
        49 => 0.0
        50 => null
        51 => 0.0
        52 => 0.0
        53 => null
        54 => null
        55 => "SILVA, I. C. O."
        56 => "2020-09-23"
        57 => "voucher"
        58 => "Centrorhynchidae"
        59 => "Van Cleave, 1916"
        60 => "Centrorhynchidae Van Cleave, 1916"
        61 => null
        62 => null
        63 => "Centrorhynchidae"
        64 => "Polymorphida"
        65 => "Palaeacanthocephala"
        66 => "Acanthocephala"
        67 => "Animalia"
        68 => null
        69 => null
        70 => "família"
        71 => "aceito"
        72 => null
        73 => null
        74 => "ICZN"
        75 => "NCBI, 2021"
        76 => "nenhum"
        77 => "2021-07-15"
        78 => "Acanthocephala"
        79 => null
        80 => null
        81 => null
        82 => null
        83 => null
        84 => null
        85 => null
        86 => null
        87 => null
        88 => null
        89 => null
        90 => null
        91 => null
      ]
      "time" => 17.19
    ]
    5 => array:3 [
      "query" => "select * from "biological_occurrence" where "occurrenceID" = ? limit 1"
      "bindings" => array:1 [
        0 => "br:UFMS:ZUFMS:ZUFMS-ACA00004"
      ]
      "time" => 0.65
    ]
    6 => array:3 [
      "query" => "insert into "biological_occurrence_view" ("informationWithheld", "basisOfRecord", "institutionCode", "collectionCode", "datasetName", "catalogNumber", "otherCatalogNumbers", "recordedBy", "recordNumber", "preparations", "individualCount", "sex", "lifeStage", "reproductiveCondition", "establishmentMeans", "behavior", "occurrenceRemarks", "disposition", "associatedReferences", "associatedMedia", "occurrenceID", "associatedOccurrences", "previousIdentifications", "fieldNumber", "day", "month", "year", "verbatimEventDate", "samplingProtocol", "habitat", "eventRemarks", "fieldNotes", "measurementRemarks", "continent", "country", "countryCode", "verbatimLocality", "stateProvince", "county", "municipality", "locality", "decimalLatitude", "decimalLongitude", "verbatimLatitude", "verbatimLongitude", "coordinatePrecision", "geodeticDatum", "footprintWKT", "minimumElevationInMeters", "maximumElevationInMeters", "waterBody", "minimumDepthInMeters", "maximumDepthInMeters", "locationRemarks", "identificationQualifier", "identifiedBy", "dateIdentified", "typeStatus", "scientificName", "scientificNameAuthorship", "acceptedNameUsage", "subgenus", "genus", "family", "order", "class", "phylum", "kingdom", "specificEpithet", "infraspecificEpithet", "taxonRank", "taxonomicStatus", "originalNameUsage", "vernacularName", "nomenclaturalCode", "nameAccordingTo", "relationshipOfResource", "dcterms:modified", "artificial:section", "artificial:shelfLocation", "artificial:flaskLocation", "artificial:shippingGuide", "artificial:subfamily", "artificial:subtribe", "artificial:tribe", "artificial:superfamily", "artificial:infraorder", "artificial:superorder", "artificial:suborder", "artificial:subclass", "artificial:subphylum", "dcterms:bibliographicCitation") values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"
      "bindings" => array:92 [
        0 => "nenhuma"
        1 => "PreservedSpecimen"
        2 => "UFMS"
        3 => "ZUFMS"
        4 => "Laboratório de Parasitologia Animal; Doutorado Isabela Caroline Oliveira da Silva"
        5 => "ZUFMS-ACA00004"
        6 => null
        7 => "SILVA, I. C. O."
        8 => "208"
        9 => "animal inteiro (ETOH 70%)"
        10 => "1"
        11 => null
        12 => "adulto"
        13 => "não reprodutivo"
        14 => "selvagem"
        15 => "parasitando"
        16 => "não informado"
        17 => "em tombamento"
        18 => null
        19 => null
        20 => "br:UFMS:ZUFMS:ZUFMS-ACA00004"
        21 => null
        22 => null
        23 => null
        24 => 27
        25 => 1
        26 => 2019
        27 => "27.I.2019"
        28 => "necropsia"
        29 => "Cerrado"
        30 => null
        31 => null
        32 => "não informado"
        33 => "América do Sul"
        34 => "Brasil"
        35 => "BRA"
        36 => "Brasil"
        37 => "Mato Grosso do Sul"
        38 => "Alcinópolis"
        39 => ""
        40 => "Parque Estadual das Nascentes do Rio Taquari"
        41 => -18.165139
        42 => -53.415806
        43 => "18°09'54.5"S"
        44 => "53°24'56.9"W"
        45 => 0.0
        46 => "WGS84"
        47 => null
        48 => 0.0
        49 => 0.0
        50 => null
        51 => 0.0
        52 => 0.0
        53 => null
        54 => "sp."
        55 => "SILVA, I. C. O."
        56 => "2020-09-23"
        57 => "voucher"
        58 => "Oligacanthorhynchus"
        59 => "Travassos, 1915"
        60 => "Oligacanthorhynchus sp. Travassos, 1915"
        61 => null
        62 => "Oligacanthorhynchus"
        63 => "Oligacanthorhynchidae"
        64 => "Oligacanthorhynchida"
        65 => "Archiacanthocephala"
        66 => "Acanthocephala"
        67 => "Animalia"
        68 => null
        69 => null
        70 => "gênero"
        71 => "aceito"
        72 => null
        73 => null
        74 => "ICZN"
        75 => "NCBI, 2021"
        76 => "nenhum"
        77 => "2021-07-15"
        78 => "Acanthocephala"
        79 => null
        80 => null
        81 => null
        82 => null
        83 => null
        84 => null
        85 => null
        86 => null
        87 => null
        88 => null
        89 => null
        90 => null
        91 => null
      ]
      "time" => 15.13
    ]
    7 => array:3 [
      "query" => "select * from "biological_occurrence" where "occurrenceID" = ? limit 1"
      "bindings" => array:1 [
        0 => "br:UFMS:ZUFMS:ZUFMS-ACA00005"
      ]
      "time" => 0.38
    ]
    8 => array:3 [
      "query" => "insert into "biological_occurrence_view" ("informationWithheld", "basisOfRecord", "institutionCode", "collectionCode", "datasetName", "catalogNumber", "otherCatalogNumbers", "recordedBy", "recordNumber", "preparations", "individualCount", "sex", "lifeStage", "reproductiveCondition", "establishmentMeans", "behavior", "occurrenceRemarks", "disposition", "associatedReferences", "associatedMedia", "occurrenceID", "associatedOccurrences", "previousIdentifications", "fieldNumber", "day", "month", "year", "verbatimEventDate", "samplingProtocol", "habitat", "eventRemarks", "fieldNotes", "measurementRemarks", "continent", "country", "countryCode", "verbatimLocality", "stateProvince", "county", "municipality", "locality", "decimalLatitude", "decimalLongitude", "verbatimLatitude", "verbatimLongitude", "coordinatePrecision", "geodeticDatum", "footprintWKT", "minimumElevationInMeters", "maximumElevationInMeters", "waterBody", "minimumDepthInMeters", "maximumDepthInMeters", "locationRemarks", "identificationQualifier", "identifiedBy", "dateIdentified", "typeStatus", "scientificName", "scientificNameAuthorship", "acceptedNameUsage", "subgenus", "genus", "family", "order", "class", "phylum", "kingdom", "specificEpithet", "infraspecificEpithet", "taxonRank", "taxonomicStatus", "originalNameUsage", "vernacularName", "nomenclaturalCode", "nameAccordingTo", "relationshipOfResource", "dcterms:modified", "artificial:section", "artificial:shelfLocation", "artificial:flaskLocation", "artificial:shippingGuide", "artificial:subfamily", "artificial:subtribe", "artificial:tribe", "artificial:superfamily", "artificial:infraorder", "artificial:superorder", "artificial:suborder", "artificial:subclass", "artificial:subphylum", "dcterms:bibliographicCitation") values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"
      "bindings" => array:92 [
        0 => "nenhuma"
        1 => "PreservedSpecimen"
        2 => "UFMS"
        3 => "ZUFMS"
        4 => "Laboratório de Parasitologia Animal; Doutorado Isabela Caroline Oliveira da Silva"
        5 => "ZUFMS-ACA00005"
        6 => null
        7 => "SILVA, I. C. O."
        8 => "219"
        9 => "animal inteiro (ETOH 70%)"
        10 => "1"
        11 => null
        12 => "adulto"
        13 => "indeterminado"
        14 => "selvagem"
        15 => "parasitando"
        16 => "não informado"
        17 => "em tombamento"
        18 => null
        19 => null
        20 => "br:UFMS:ZUFMS:ZUFMS-ACA00005"
        21 => null
        22 => null
        23 => null
        24 => 29
        25 => 1
        26 => 2019
        27 => "29.I.2019"
        28 => "necropsia"
        29 => "Cerrado"
        30 => null
        31 => null
        32 => "não informado"
        33 => "América do Sul"
        34 => "Brasil"
        35 => "BRA"
        36 => "Brasil"
        37 => "Mato Grosso do Sul"
        38 => "Alcinópolis"
        39 => ""
        40 => "Parque Estadual das Nascentes do Rio Taquari"
        41 => -18.165139
        42 => -53.415806
        43 => "18°09'54.5"S"
        44 => "53°24'56.9"W"
        45 => 0.0
        46 => "WGS84"
        47 => null
        48 => 0.0
        49 => 0.0
        50 => null
        51 => 0.0
        52 => 0.0
        53 => null
        54 => null
        55 => "SILVA, I. C. O."
        56 => "2020-09-23"
        57 => "voucher"
        58 => "Oligacanthorhynchidae"
        59 => "Southwell & Macfie, 1925"
        60 => "Oligacanthorhynchidae Southwell & Macfie, 1925"
        61 => null
        62 => null
        63 => "Oligacanthorhynchidae"
        64 => "Oligacanthorhynchida"
        65 => "Archiacanthocephala"
        66 => "Acanthocephala"
        67 => "Animalia"
        68 => null
        69 => null
        70 => "família"
        71 => "aceito"
        72 => null
        73 => null
        74 => "ICZN"
        75 => "NCBI, 2021"
        76 => "nenhum"
        77 => "2021-07-15"
        78 => "Acanthocephala"
        79 => null
        80 => null
        81 => null
        82 => null
        83 => null
        84 => null
        85 => null
        86 => null
        87 => null
        88 => null
        89 => null
        90 => null
        91 => null
      ]
      "time" => 10.86
    ]
  ]
  5 => array:11 [
    0 => array:3 [
      "query" => "insert into "biological_occurrence_view" ("informationWithheld", "basisOfRecord", "institutionCode", "collectionCode", "datasetName", "catalogNumber", "otherCatalogNumbers", "recordedBy", "recordNumber", "preparations", "individualCount", "sex", "lifeStage", "reproductiveCondition", "establishmentMeans", "behavior", "occurrenceRemarks", "disposition", "associatedReferences", "associatedMedia", "occurrenceID", "associatedOccurrences", "previousIdentifications", "fieldNumber", "day", "month", "year", "verbatimEventDate", "samplingProtocol", "habitat", "eventRemarks", "fieldNotes", "measurementRemarks", "continent", "country", "countryCode", "verbatimLocality", "stateProvince", "county", "municipality", "locality", "decimalLatitude", "decimalLongitude", "verbatimLatitude", "verbatimLongitude", "coordinatePrecision", "geodeticDatum", "footprintWKT", "minimumElevationInMeters", "maximumElevationInMeters", "waterBody", "minimumDepthInMeters", "maximumDepthInMeters", "locationRemarks", "identificationQualifier", "identifiedBy", "dateIdentified", "typeStatus", "scientificName", "scientificNameAuthorship", "acceptedNameUsage", "subgenus", "genus", "family", "order", "class", "phylum", "kingdom", "specificEpithet", "infraspecificEpithet", "taxonRank", "taxonomicStatus", "originalNameUsage", "vernacularName", "nomenclaturalCode", "nameAccordingTo", "relationshipOfResource", "dcterms:modified", "artificial:section", "artificial:shelfLocation", "artificial:flaskLocation", "artificial:shippingGuide", "artificial:subfamily", "artificial:subtribe", "artificial:tribe", "artificial:superfamily", "artificial:infraorder", "artificial:superorder", "artificial:suborder", "artificial:subclass", "artificial:subphylum", "dcterms:bibliographicCitation") values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"
      "bindings" => array:92 [
        0 => "nenhuma"
        1 => "PreservedSpecimen"
        2 => "UFMS"
        3 => "ZUFMS"
        4 => "material em estudo por Carla Kampião"
        5 => "ZUFMS-ACA00001"
        6 => null
        7 => "Campião, K. et al."
        8 => "93"
        9 => "animal inteiro (ETOH 70%)"
        10 => "9"
        11 => null
        12 => null
        13 => null
        14 => "selvagem"
        15 => "não informado"
        16 => "parasita de Phyllomedusa azurea (Amphibia: Hylidae)"
        17 => "em coleção"
        18 => null
        19 => null
        20 => "br:UFMS:ZUFMS:ZUFMS-ACA00001"
        21 => null
        22 => null
        23 => null
        24 => 3
        25 => 2
        26 => 2011
        27 => "03.II.2011"
        28 => null
        29 => null
        30 => null
        31 => null
        32 => null
        33 => "América do Sul"
        34 => "Brasil"
        35 => "BRA"
        36 => "Brasil"
        37 => "Mato Grosso do Sul"
        38 => "Corumbá"
        39 => ""
        40 => "Fazenda Alegria"
        41 => -18.983333
        42 => -56.65
        43 => "18°59'00"S"
        44 => "56°39'00"W"
        45 => 0.0
        46 => "WGS84"
        47 => null
        48 => 0.0
        49 => 0.0
        50 => null
        51 => 0.0
        52 => 0.0
        53 => null
        54 => null
        55 => "Campião, K."
        56 => null
        57 => null
        58 => "Acanthocephala"
        59 => null
        60 => "Acanthocephala"
        61 => null
        62 => null
        63 => null
        64 => null
        65 => null
        66 => "Acanthocephala"
        67 => "Animalia"
        68 => null
        69 => null
        70 => "filo"
        71 => null
        72 => null
        73 => null
        74 => "ICZN"
        75 => null
        76 => "nenhum"
        77 => "2017-08-30"
        78 => "Acanthocephala"
        79 => null
        80 => null
        81 => null
        82 => null
        83 => null
        84 => null
        85 => null
        86 => null
        87 => null
        88 => null
        89 => null
        90 => null
        91 => null
      ]
      "time" => 45.67
    ]
    1 => array:3 [
      "query" => "select * from "biological_occurrence" where "occurrenceID" = ? limit 1"
      "bindings" => array:1 [
        0 => "br:UFMS:ZUFMS:ZUFMS-ACA00002"
      ]
      "time" => 0.3
    ]
    2 => array:3 [
      "query" => "insert into "biological_occurrence_view" ("informationWithheld", "basisOfRecord", "institutionCode", "collectionCode", "datasetName", "catalogNumber", "otherCatalogNumbers", "recordedBy", "recordNumber", "preparations", "individualCount", "sex", "lifeStage", "reproductiveCondition", "establishmentMeans", "behavior", "occurrenceRemarks", "disposition", "associatedReferences", "associatedMedia", "occurrenceID", "associatedOccurrences", "previousIdentifications", "fieldNumber", "day", "month", "year", "verbatimEventDate", "samplingProtocol", "habitat", "eventRemarks", "fieldNotes", "measurementRemarks", "continent", "country", "countryCode", "verbatimLocality", "stateProvince", "county", "municipality", "locality", "decimalLatitude", "decimalLongitude", "verbatimLatitude", "verbatimLongitude", "coordinatePrecision", "geodeticDatum", "footprintWKT", "minimumElevationInMeters", "maximumElevationInMeters", "waterBody", "minimumDepthInMeters", "maximumDepthInMeters", "locationRemarks", "identificationQualifier", "identifiedBy", "dateIdentified", "typeStatus", "scientificName", "scientificNameAuthorship", "acceptedNameUsage", "subgenus", "genus", "family", "order", "class", "phylum", "kingdom", "specificEpithet", "infraspecificEpithet", "taxonRank", "taxonomicStatus", "originalNameUsage", "vernacularName", "nomenclaturalCode", "nameAccordingTo", "relationshipOfResource", "dcterms:modified", "artificial:section", "artificial:shelfLocation", "artificial:flaskLocation", "artificial:shippingGuide", "artificial:subfamily", "artificial:subtribe", "artificial:tribe", "artificial:superfamily", "artificial:infraorder", "artificial:superorder", "artificial:suborder", "artificial:subclass", "artificial:subphylum", "dcterms:bibliographicCitation") values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"
      "bindings" => array:92 [
        0 => "nenhuma"
        1 => "PreservedSpecimen"
        2 => "UFMS"
        3 => "ZUFMS"
        4 => "material estudado por Isabela Caroline Oliveira da Silva"
        5 => "ZUFMS-ACA00002"
        6 => null
        7 => "Silva, I. C. O."
        8 => ""
        9 => "animal inteiro (ETOH 70%)"
        10 => "1"
        11 => null
        12 => "jovem"
        13 => "não reprodutivo"
        14 => "selvagem"
        15 => "não informado"
        16 => "parasita de Pseudis paradoxa (Amphibia: Hylidae)"
        17 => "em coleção"
        18 => null
        19 => null
        20 => "br:UFMS:ZUFMS:ZUFMS-ACA00002"
        21 => null
        22 => null
        23 => null
        24 => 17
        25 => 2
        26 => 2012
        27 => "17.II.2012"
        28 => "necropsia"
        29 => "Pantanal"
        30 => null
        31 => null
        32 => null
        33 => "América do Sul"
        34 => "Brasil"
        35 => "BRA"
        36 => "Brasil"
        37 => "Mato Grosso do Sul"
        38 => "Corumbá"
        39 => ""
        40 => "Fazenda Alegria"
        41 => -18.983333
        42 => -56.65
        43 => "18°59'00"S"
        44 => "56°39'00"W"
        45 => 0.0
        46 => "WGS84"
        47 => null
        48 => 89.0
        49 => 106.0
        50 => null
        51 => 0.0
        52 => 0.0
        53 => null
        54 => null
        55 => "Silva, I. C. O."
        56 => "2016"
        57 => null
        58 => "Acanthocephala"
        59 => null
        60 => "Acanthocephala"
        61 => null
        62 => null
        63 => null
        64 => null
        65 => null
        66 => "Acanthocephala"
        67 => "Animalia"
        68 => null
        69 => null
        70 => "filo"
        71 => null
        72 => null
        73 => null
        74 => "ICZN"
        75 => null
        76 => "nenhum"
        77 => "2017-08-30"
        78 => "Acanthocephala"
        79 => null
        80 => null
        81 => null
        82 => null
        83 => null
        84 => null
        85 => null
        86 => null
        87 => null
        88 => null
        89 => null
        90 => null
        91 => null
      ]
      "time" => 15.73
    ]
    3 => array:3 [
      "query" => "select * from "biological_occurrence" where "occurrenceID" = ? limit 1"
      "bindings" => array:1 [
        0 => "br:UFMS:ZUFMS:ZUFMS-ACA00003"
      ]
      "time" => 0.52
    ]
    4 => array:3 [
      "query" => "insert into "biological_occurrence_view" ("informationWithheld", "basisOfRecord", "institutionCode", "collectionCode", "datasetName", "catalogNumber", "otherCatalogNumbers", "recordedBy", "recordNumber", "preparations", "individualCount", "sex", "lifeStage", "reproductiveCondition", "establishmentMeans", "behavior", "occurrenceRemarks", "disposition", "associatedReferences", "associatedMedia", "occurrenceID", "associatedOccurrences", "previousIdentifications", "fieldNumber", "day", "month", "year", "verbatimEventDate", "samplingProtocol", "habitat", "eventRemarks", "fieldNotes", "measurementRemarks", "continent", "country", "countryCode", "verbatimLocality", "stateProvince", "county", "municipality", "locality", "decimalLatitude", "decimalLongitude", "verbatimLatitude", "verbatimLongitude", "coordinatePrecision", "geodeticDatum", "footprintWKT", "minimumElevationInMeters", "maximumElevationInMeters", "waterBody", "minimumDepthInMeters", "maximumDepthInMeters", "locationRemarks", "identificationQualifier", "identifiedBy", "dateIdentified", "typeStatus", "scientificName", "scientificNameAuthorship", "acceptedNameUsage", "subgenus", "genus", "family", "order", "class", "phylum", "kingdom", "specificEpithet", "infraspecificEpithet", "taxonRank", "taxonomicStatus", "originalNameUsage", "vernacularName", "nomenclaturalCode", "nameAccordingTo", "relationshipOfResource", "dcterms:modified", "artificial:section", "artificial:shelfLocation", "artificial:flaskLocation", "artificial:shippingGuide", "artificial:subfamily", "artificial:subtribe", "artificial:tribe", "artificial:superfamily", "artificial:infraorder", "artificial:superorder", "artificial:suborder", "artificial:subclass", "artificial:subphylum", "dcterms:bibliographicCitation") values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"
      "bindings" => array:92 [
        0 => "nenhuma"
        1 => "PreservedSpecimen"
        2 => "UFMS"
        3 => "ZUFMS"
        4 => "Laboratório de Parasitologia Animal; Doutorado Isabela Caroline Oliveira da Silva"
        5 => "ZUFMS-ACA00003"
        6 => null
        7 => "SILVA, I. C. O."
        8 => "206"
        9 => "animal inteiro (ETOH 70%)"
        10 => "1"
        11 => null
        12 => "adulto"
        13 => "indeterminado"
        14 => "selvagem"
        15 => "parasitando"
        16 => "não informado"
        17 => "em tombamento"
        18 => null
        19 => null
        20 => "br:UFMS:ZUFMS:ZUFMS-ACA00003"
        21 => null
        22 => null
        23 => null
        24 => 26
        25 => 1
        26 => 2019
        27 => "26.I.2019"
        28 => "necropsia"
        29 => "Cerrado"
        30 => null
        31 => null
        32 => "não informado"
        33 => "América do Sul"
        34 => "Brasil"
        35 => "BRA"
        36 => "Brasil"
        37 => "Mato Grosso do Sul"
        38 => "Alcinópolis"
        39 => ""
        40 => "Parque Estadual das Nascentes do Rio Taquari"
        41 => -18.165139
        42 => -53.415806
        43 => "18°09'54.5"S"
        44 => "53°24'56.9"W"
        45 => 0.0
        46 => "WGS84"
        47 => null
        48 => 0.0
        49 => 0.0
        50 => null
        51 => 0.0
        52 => 0.0
        53 => null
        54 => null
        55 => "SILVA, I. C. O."
        56 => "2020-09-23"
        57 => "voucher"
        58 => "Centrorhynchidae"
        59 => "Van Cleave, 1916"
        60 => "Centrorhynchidae Van Cleave, 1916"
        61 => null
        62 => null
        63 => "Centrorhynchidae"
        64 => "Polymorphida"
        65 => "Palaeacanthocephala"
        66 => "Acanthocephala"
        67 => "Animalia"
        68 => null
        69 => null
        70 => "família"
        71 => "aceito"
        72 => null
        73 => null
        74 => "ICZN"
        75 => "NCBI, 2021"
        76 => "nenhum"
        77 => "2021-07-15"
        78 => "Acanthocephala"
        79 => null
        80 => null
        81 => null
        82 => null
        83 => null
        84 => null
        85 => null
        86 => null
        87 => null
        88 => null
        89 => null
        90 => null
        91 => null
      ]
      "time" => 17.19
    ]
    5 => array:3 [
      "query" => "select * from "biological_occurrence" where "occurrenceID" = ? limit 1"
      "bindings" => array:1 [
        0 => "br:UFMS:ZUFMS:ZUFMS-ACA00004"
      ]
      "time" => 0.65
    ]
    6 => array:3 [
      "query" => "insert into "biological_occurrence_view" ("informationWithheld", "basisOfRecord", "institutionCode", "collectionCode", "datasetName", "catalogNumber", "otherCatalogNumbers", "recordedBy", "recordNumber", "preparations", "individualCount", "sex", "lifeStage", "reproductiveCondition", "establishmentMeans", "behavior", "occurrenceRemarks", "disposition", "associatedReferences", "associatedMedia", "occurrenceID", "associatedOccurrences", "previousIdentifications", "fieldNumber", "day", "month", "year", "verbatimEventDate", "samplingProtocol", "habitat", "eventRemarks", "fieldNotes", "measurementRemarks", "continent", "country", "countryCode", "verbatimLocality", "stateProvince", "county", "municipality", "locality", "decimalLatitude", "decimalLongitude", "verbatimLatitude", "verbatimLongitude", "coordinatePrecision", "geodeticDatum", "footprintWKT", "minimumElevationInMeters", "maximumElevationInMeters", "waterBody", "minimumDepthInMeters", "maximumDepthInMeters", "locationRemarks", "identificationQualifier", "identifiedBy", "dateIdentified", "typeStatus", "scientificName", "scientificNameAuthorship", "acceptedNameUsage", "subgenus", "genus", "family", "order", "class", "phylum", "kingdom", "specificEpithet", "infraspecificEpithet", "taxonRank", "taxonomicStatus", "originalNameUsage", "vernacularName", "nomenclaturalCode", "nameAccordingTo", "relationshipOfResource", "dcterms:modified", "artificial:section", "artificial:shelfLocation", "artificial:flaskLocation", "artificial:shippingGuide", "artificial:subfamily", "artificial:subtribe", "artificial:tribe", "artificial:superfamily", "artificial:infraorder", "artificial:superorder", "artificial:suborder", "artificial:subclass", "artificial:subphylum", "dcterms:bibliographicCitation") values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"
      "bindings" => array:92 [
        0 => "nenhuma"
        1 => "PreservedSpecimen"
        2 => "UFMS"
        3 => "ZUFMS"
        4 => "Laboratório de Parasitologia Animal; Doutorado Isabela Caroline Oliveira da Silva"
        5 => "ZUFMS-ACA00004"
        6 => null
        7 => "SILVA, I. C. O."
        8 => "208"
        9 => "animal inteiro (ETOH 70%)"
        10 => "1"
        11 => null
        12 => "adulto"
        13 => "não reprodutivo"
        14 => "selvagem"
        15 => "parasitando"
        16 => "não informado"
        17 => "em tombamento"
        18 => null
        19 => null
        20 => "br:UFMS:ZUFMS:ZUFMS-ACA00004"
        21 => null
        22 => null
        23 => null
        24 => 27
        25 => 1
        26 => 2019
        27 => "27.I.2019"
        28 => "necropsia"
        29 => "Cerrado"
        30 => null
        31 => null
        32 => "não informado"
        33 => "América do Sul"
        34 => "Brasil"
        35 => "BRA"
        36 => "Brasil"
        37 => "Mato Grosso do Sul"
        38 => "Alcinópolis"
        39 => ""
        40 => "Parque Estadual das Nascentes do Rio Taquari"
        41 => -18.165139
        42 => -53.415806
        43 => "18°09'54.5"S"
        44 => "53°24'56.9"W"
        45 => 0.0
        46 => "WGS84"
        47 => null
        48 => 0.0
        49 => 0.0
        50 => null
        51 => 0.0
        52 => 0.0
        53 => null
        54 => "sp."
        55 => "SILVA, I. C. O."
        56 => "2020-09-23"
        57 => "voucher"
        58 => "Oligacanthorhynchus"
        59 => "Travassos, 1915"
        60 => "Oligacanthorhynchus sp. Travassos, 1915"
        61 => null
        62 => "Oligacanthorhynchus"
        63 => "Oligacanthorhynchidae"
        64 => "Oligacanthorhynchida"
        65 => "Archiacanthocephala"
        66 => "Acanthocephala"
        67 => "Animalia"
        68 => null
        69 => null
        70 => "gênero"
        71 => "aceito"
        72 => null
        73 => null
        74 => "ICZN"
        75 => "NCBI, 2021"
        76 => "nenhum"
        77 => "2021-07-15"
        78 => "Acanthocephala"
        79 => null
        80 => null
        81 => null
        82 => null
        83 => null
        84 => null
        85 => null
        86 => null
        87 => null
        88 => null
        89 => null
        90 => null
        91 => null
      ]
      "time" => 15.13
    ]
    7 => array:3 [
      "query" => "select * from "biological_occurrence" where "occurrenceID" = ? limit 1"
      "bindings" => array:1 [
        0 => "br:UFMS:ZUFMS:ZUFMS-ACA00005"
      ]
      "time" => 0.38
    ]
    8 => array:3 [
      "query" => "insert into "biological_occurrence_view" ("informationWithheld", "basisOfRecord", "institutionCode", "collectionCode", "datasetName", "catalogNumber", "otherCatalogNumbers", "recordedBy", "recordNumber", "preparations", "individualCount", "sex", "lifeStage", "reproductiveCondition", "establishmentMeans", "behavior", "occurrenceRemarks", "disposition", "associatedReferences", "associatedMedia", "occurrenceID", "associatedOccurrences", "previousIdentifications", "fieldNumber", "day", "month", "year", "verbatimEventDate", "samplingProtocol", "habitat", "eventRemarks", "fieldNotes", "measurementRemarks", "continent", "country", "countryCode", "verbatimLocality", "stateProvince", "county", "municipality", "locality", "decimalLatitude", "decimalLongitude", "verbatimLatitude", "verbatimLongitude", "coordinatePrecision", "geodeticDatum", "footprintWKT", "minimumElevationInMeters", "maximumElevationInMeters", "waterBody", "minimumDepthInMeters", "maximumDepthInMeters", "locationRemarks", "identificationQualifier", "identifiedBy", "dateIdentified", "typeStatus", "scientificName", "scientificNameAuthorship", "acceptedNameUsage", "subgenus", "genus", "family", "order", "class", "phylum", "kingdom", "specificEpithet", "infraspecificEpithet", "taxonRank", "taxonomicStatus", "originalNameUsage", "vernacularName", "nomenclaturalCode", "nameAccordingTo", "relationshipOfResource", "dcterms:modified", "artificial:section", "artificial:shelfLocation", "artificial:flaskLocation", "artificial:shippingGuide", "artificial:subfamily", "artificial:subtribe", "artificial:tribe", "artificial:superfamily", "artificial:infraorder", "artificial:superorder", "artificial:suborder", "artificial:subclass", "artificial:subphylum", "dcterms:bibliographicCitation") values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"
      "bindings" => array:92 [
        0 => "nenhuma"
        1 => "PreservedSpecimen"
        2 => "UFMS"
        3 => "ZUFMS"
        4 => "Laboratório de Parasitologia Animal; Doutorado Isabela Caroline Oliveira da Silva"
        5 => "ZUFMS-ACA00005"
        6 => null
        7 => "SILVA, I. C. O."
        8 => "219"
        9 => "animal inteiro (ETOH 70%)"
        10 => "1"
        11 => null
        12 => "adulto"
        13 => "indeterminado"
        14 => "selvagem"
        15 => "parasitando"
        16 => "não informado"
        17 => "em tombamento"
        18 => null
        19 => null
        20 => "br:UFMS:ZUFMS:ZUFMS-ACA00005"
        21 => null
        22 => null
        23 => null
        24 => 29
        25 => 1
        26 => 2019
        27 => "29.I.2019"
        28 => "necropsia"
        29 => "Cerrado"
        30 => null
        31 => null
        32 => "não informado"
        33 => "América do Sul"
        34 => "Brasil"
        35 => "BRA"
        36 => "Brasil"
        37 => "Mato Grosso do Sul"
        38 => "Alcinópolis"
        39 => ""
        40 => "Parque Estadual das Nascentes do Rio Taquari"
        41 => -18.165139
        42 => -53.415806
        43 => "18°09'54.5"S"
        44 => "53°24'56.9"W"
        45 => 0.0
        46 => "WGS84"
        47 => null
        48 => 0.0
        49 => 0.0
        50 => null
        51 => 0.0
        52 => 0.0
        53 => null
        54 => null
        55 => "SILVA, I. C. O."
        56 => "2020-09-23"
        57 => "voucher"
        58 => "Oligacanthorhynchidae"
        59 => "Southwell & Macfie, 1925"
        60 => "Oligacanthorhynchidae Southwell & Macfie, 1925"
        61 => null
        62 => null
        63 => "Oligacanthorhynchidae"
        64 => "Oligacanthorhynchida"
        65 => "Archiacanthocephala"
        66 => "Acanthocephala"
        67 => "Animalia"
        68 => null
        69 => null
        70 => "família"
        71 => "aceito"
        72 => null
        73 => null
        74 => "ICZN"
        75 => "NCBI, 2021"
        76 => "nenhum"
        77 => "2021-07-15"
        78 => "Acanthocephala"
        79 => null
        80 => null
        81 => null
        82 => null
        83 => null
        84 => null
        85 => null
        86 => null
        87 => null
        88 => null
        89 => null
        90 => null
        91 => null
      ]
      "time" => 10.86
    ]
    9 => array:3 [
      "query" => "select * from "biological_occurrence" where "occurrenceID" = ? limit 1"
      "bindings" => array:1 [
        0 => "br:UFMS:ZUFMS:ZUFMS-ACA00006"
      ]
      "time" => 0.37
    ]
    10 => array:3 [
      "query" => "insert into "biological_occurrence_view" ("informationWithheld", "basisOfRecord", "institutionCode", "collectionCode", "datasetName", "catalogNumber", "otherCatalogNumbers", "recordedBy", "recordNumber", "preparations", "individualCount", "sex", "lifeStage", "reproductiveCondition", "establishmentMeans", "behavior", "occurrenceRemarks", "disposition", "associatedReferences", "associatedMedia", "occurrenceID", "associatedOccurrences", "previousIdentifications", "fieldNumber", "day", "month", "year", "verbatimEventDate", "samplingProtocol", "habitat", "eventRemarks", "fieldNotes", "measurementRemarks", "continent", "country", "countryCode", "verbatimLocality", "stateProvince", "county", "municipality", "locality", "decimalLatitude", "decimalLongitude", "verbatimLatitude", "verbatimLongitude", "coordinatePrecision", "geodeticDatum", "footprintWKT", "minimumElevationInMeters", "maximumElevationInMeters", "waterBody", "minimumDepthInMeters", "maximumDepthInMeters", "locationRemarks", "identificationQualifier", "identifiedBy", "dateIdentified", "typeStatus", "scientificName", "scientificNameAuthorship", "acceptedNameUsage", "subgenus", "genus", "family", "order", "class", "phylum", "kingdom", "specificEpithet", "infraspecificEpithet", "taxonRank", "taxonomicStatus", "originalNameUsage", "vernacularName", "nomenclaturalCode", "nameAccordingTo", "relationshipOfResource", "dcterms:modified", "artificial:section", "artificial:shelfLocation", "artificial:flaskLocation", "artificial:shippingGuide", "artificial:subfamily", "artificial:subtribe", "artificial:tribe", "artificial:superfamily", "artificial:infraorder", "artificial:superorder", "artificial:suborder", "artificial:subclass", "artificial:subphylum", "dcterms:bibliographicCitation") values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"
      "bindings" => array:92 [
        0 => "nenhuma"
        1 => "PreservedSpecimen"
        2 => "UFMS"
        3 => "ZUFMS"
        4 => "Laboratório de Parasitologia Animal; Doutorado Isabela Caroline Oliveira da Silva"
        5 => "ZUFMS-ACA00006"
        6 => null
        7 => "SILVA, I. C. O."
        8 => "234"
        9 => "animal inteiro (ETOH 70%)"
        10 => "1"
        11 => null
        12 => "adulto"
        13 => "indeterminado"
        14 => "selvagem"
        15 => "parasitando"
        16 => "não informado"
        17 => "em tombamento"
        18 => null
        19 => null
        20 => "br:UFMS:ZUFMS:ZUFMS-ACA00006"
        21 => null
        22 => null
        23 => null
        24 => 2
        25 => 2
        26 => 2019
        27 => "02.II.2019"
        28 => "necropsia"
        29 => "Cerrado"
        30 => null
        31 => null
        32 => "não informado"
        33 => "América do Sul"
        34 => "Brasil"
        35 => "BRA"
        36 => "Brasil"
        37 => "Mato Grosso do Sul"
        38 => "Alcinópolis"
        39 => ""
        40 => "Parque Estadual das Nascentes do Rio Taquari"
        41 => -18.165139
        42 => -53.415806
        43 => "18°09'54.5"S"
        44 => "53°24'56.9"W"
        45 => 0.0
        46 => "WGS84"
        47 => null
        48 => 0.0
        49 => 0.0
        50 => null
        51 => 0.0
        52 => 0.0
        53 => null
        54 => "sp."
        55 => "SILVA, I. C. O."
        56 => "2020-09-23"
        57 => "voucher"
        58 => "Centrorhynchus"
        59 => "Lühe, 1911"
        60 => "Centrorhynchus sp. Lühe, 1911"
        61 => null
        62 => "Centrorhynchus"
        63 => "Centrorhynchidae"
        64 => "Polymorphida"
        65 => "Palaeacanthocephala"
        66 => "Acanthocephala"
        67 => "Animalia"
        68 => null
        69 => null
        70 => "gênero"
        71 => "aceito"
        72 => null
        73 => null
        74 => "ICZN"
        75 => "NCBI, 2021"
        76 => "nenhum"
        77 => "2021-07-15"
        78 => "Acanthocephala"
        79 => null
        80 => null
        81 => null
        82 => null
        83 => null
        84 => null
        85 => null
        86 => null
        87 => null
        88 => null
        89 => null
        90 => null
        91 => null
      ]
      "time" => 14.46
    ]
  ]
]